### ISSUE TITLE
API Clarification - Vehicle Service Brand

### ISSUE THREAD

**Issue by jspetrak** [UnionInternationalCheminsdeFer/OSDM#211]
Trip Segment has property `vehicle` containing a service details. One of properties is `serviceBrand`.

In mocks as well as swagger example, string values are used to represent serviceBrand, e.g. `IC`, `EC`, ...

However, datatype of the property is integer. And the description refers to numeric values of UIC Service Brand Code List:

> Service brand codes allowed in response, code list can be found on [https://uic.org/passenger/passenger-services-group/article/service-brand-code-list] (https://uic.org/passenger/passenger-services-group/article/service-brand-code-list)

What is correct value?

**Comment by CGantert345** [comment]
The service brand is a numeric code (managed by UIC but also part of EU TAP-TSI). We need to fix the mocks and examples.

**Comment by jspetrak** [comment]
@CGantert345 Thanks for quick reply! How difficult is to expand the code list with missing values? Most of the brands used on SŽ (Czechia) network are missing.

**Comment by CGantert345** [comment]
New service brand codes can be requested vai a form on the UIC website: https://uic.org/passenger/passenger-services-group/article/service-brand-code-list?recherche=service%20brand
