### ISSUE TITLE
API Clarification: Coach Layouts

### ISSUE THREAD

**Issue by jspetrak** [UnionInternationalCheminsdeFer/OSDM#244]
Bileto is implementing Coach Layout support in addition to Place Map of Reservation, and we seek clarification. The information is lost needed for multi-coach compositions.

Question - What does represent Coach Layout

Is Coach Layout ID representing single type in carrier inventory, e.g. Sentra S431DT or CZ-CD 21-91 Bmz245 coach
or
single carriage in composition running, e.g. "Coach 369 of train EC170 on 2022-01-01 which is CZ-CD 21-91 Bmz245" or "Service 1 on 2022-01-01 has two bus coaches, of which Bus 2 is Setra S515HD" (additional capacity for peak service)?

Question - Can we have endpoint to obtain entire composition

Currently there is either `/coachLayouts` endpoint to obtain entire carrier inventory which may have tens or hundreds of coach layouts (if coach layout represents type, and not type on train/bus service on given day).

We also have `/coachLayouts/{layoutId}` representing single Coach layout.

If the composition has 2 or more carriages, we would need either to load coach layouts one-by-one, or entire inventory and then dump most of data.

Can we have endpoint, e.g. `/offers/{offerId}/reservations/{reservationId}/place-map/coach-layouts`, to obtain all coach layouts necessary for graphical seat selection for given reservation?

Side note: it could be interesting to be able to inquiry the trip segment composition also outside of scope of offered reservation.

**Comment by CGantert345** [comment]
Hello Josef,

the coach layout represents the graphical layout of a coach type.

So all layouts must be preloaded (e.g. once a week or day).

As the layout data are stable but the data volume is large it is desiged not to load the layouts with each individual request of a customer. In the request for the places you would get the available places for a reservation offer and then you can link it to the layout you already preloaded to display it graphically.
