### ISSUE TITLE
Reservation.commonOfferPartAttributes.passengerIds accepts single ID only

### ISSUE THREAD

**Issue by jspetrak** [UnionInternationalCheminsdeFer/OSDM#249]
`Reservation.commonOfferPartAttributes.passengerIds` in Offer response expects to inser 1..N passenger IDs however, the value is string not array<string>.

**Comment by jspetrak** [comment]
@schlpbch Hello Andreas, could we review and possibly fix this discrepancy in OSDM 1.4 before it is published? I have just found that while working internally on diff between 1.2 and 1.4 openapi spec so we can upgrade out interfaces.

**Comment by schlpbch** [comment]
Good catch!
