### ISSUE TITLE
Clarification: Offer Reservation.reservationDetail required

### ISSUE THREAD

**Issue by jspetrak** [UnionInternationalCheminsdeFer/OSDM#262]
I am compiling OSDM 1.2 -> 1.4 migration tasks for Bileto developers.

In POST /trip-offers-collection response Reservation object has reservationDetail marked as required. However, ReservationDetail has both accommodationType and accommodationSubType marked as required. Type is easy to fill in for standard day train with `SEAT` value, however subtype does not have general value and expects to have seat preselected for the offer.

Does OSDM expect the Offer to have pre-selected seats?

**Comment by schlpbch** [comment]
Adding a AccommodationSubClass of Type ANY_SEAT
