### ISSUE TITLE
Update terminology

### ISSUE THREAD

**Issue by schlpbch** [UnionInternationalCheminsdeFer/OSDM#278]
Update terminology to new lingo.

**Comment by CGantert345** [comment]
the agreed mapping on the ERA meeting 8.6.2022 is:
 
•	OSDM-Allocator is kept but the description will be extended to say that this corresponds to the TAP-TSI distributor and issuer roles
•	OSDM-Ticket Vendor --> Retailer           (ERA plans to use the term Ticket vendor in a more generic term similar to railway undertakng and not as a role name)
•	OSDM-Distributor --> Retailer
•	The following roles keep their names but we need to copy the TAP-TSI definitions (which are almost identical to ours):
o	Carrier
o	Passenger
o	Customer
o	TCO
•	Fare Provider and Local Transport Authority are kept 
 
 
Stefan Jugelt from ERA will do the changes in the provided version 1.5 for TAP-TSI himself until the final ERA meeting on 28.6.. 
 
The alignment with CIT is ongoing, but there is not enough time to change the TAP-TSI role definition in the current TAP-TSI revision.

**Comment by schlpbch** [comment]
Terminology updated with OSDM 2.0.
