### ISSUE TITLE
API to obtain balance of pass/multi-ride ticket/travel account

### ISSUE THREAD

**Issue by jspetrak** [UnionInternationalCheminsdeFer/OSDM#317]
Once fulfilled, passes, multi-ride admissions and other travel accounts are provided in the Offer requests as ReductionCards.

This newly proposed API is going to provide balabce information (end of validity, remaining number of rides, unspent credit/money amount, etc.)

**Comment by jspetrak** [comment]
URL: `GET /reductionCards/?issuerRef={{issuer_ref}}&identifier={{identifier}}`

- issuerRef (required): reference to issuer/maintainer of the reduction card or other multi-ticket/pass
- identifier (required): number or code to identify the card

Response:
```yaml
CardBalanceType:
    type: string
    x-extensible-enum:
        - NONE
        - TRIP
        - CREDIT
        - MONEY
```

```json
{
    "issuerRef": "urn:uic:rics:1234",
    "identifier": "1234567890",
    "holderName": "Holder Name",
    "expirationDate": "9999-12-31",
    "balanceType": "MONEY",
    "balanceCurrency": "urn:iso:std:iso:4217:EUR",
    "totalBalance": "100",
    "remainingBalance": "60",
    "stopPlaceCoverage": [],
    "zoneCoverage": []
}
```

Doc:

- issuerRef (required): reference to issuer/maintainer of the reduction card or other multi-ticket/pass
- identifier (required): number or code to identify the card
- holderName (optional): name of the card/product holder of not anonymous
- expirationDate (required): date of product expiration, or 9999-12-31 for products not constrained by time 
- balanceType (required): type/unit to represent the balance of the card
- balanceCurrency (optional): provided if balanceType is `MONEY`
- totalBalance, remainingBalance (optional): of balanceType is not `NONE`
- stopPlaceCoverage (optional, array): list of '#/components/schemas/StopPlaceRef' to list places covered by the product
- zoneCoverage (optional, array): list of transportation zones covered by the product (there is not a ZoneRef yet) or we want combined StopPlaceOrZoneRef? or zone will be referenceable with StopPlaceRef?

For review:
[EN 1545-1:2005 - Identification card systems - Surface transport applications - Part 1: Elementary data types, general code lists and general data elements](https://standards.iteh.ai/catalog/standards/cen/4c1a2cc5-2054-43d3-b631-e2ec4f5becb1/en-1545-1-2005)

**Comment by Linus-Turnit** [comment]
I am used to see 2 used of 10. You have a more positive approach 8 left of 10 , I like it :-)

For a multi-ride ticket with call off need (you have to book a trip to count the usage each time), a list of these bookings would be good to have. If it is only the id's or a more descriptive response is the question. I think a descriptive one is good to reduce the network traffic:
bookingId
offerId alt fulfillmentId
productDescription
purchaseTime
travelDateTime
price (probably 0.00 EUR)

**Comment by ralfbayer-db** [comment]
I would suggest that we interpret (and document accordingly) the unit type "CREDIT" as a carrier/PTA defined unit, which can be consumed in multiples of one depending on the type of ticket purchased with the current reduction card. This would cover the case of the Munic "Streifenkarte", which comes with 10 "Stripes" and you have to cancel 1-10 stripes per trip (if you really, really want to know: https://www.mvv-muenchen.de/en/tickets-and-fares/tickets-daytickets/stripe-ticket/index.html. Trust me, you don't).

**Comment by ralfbayer-db** [comment]
We also agreed not to confuse the concept of the existing master data type "ReductionCards" (which really is "ReductionCardTypes") with the actual balance of existing instances of reduction cards or multi ride tickets.

I believe we agreed to rename the existing master data endpoint to ReductionCardTypes, and to add the new endpoint as GET /ReductionCards/{reductionCardId}.

**Comment by jspetrak** [comment]
Regarding `CREDIT` UnitType I would suggest to rename it to `NAMED` and add an optional property unitName so we can call it Credits, Stripes, LEO Korunas (LEO Express had crowns, not credits), or whatever else.

Below is the updated proposal:

```yaml
ReductionCardUnit:
    type: string
    x-extensible-enum:
        - NONE
        - TRIP
        - MONEY
        - NAMED
```

Master data's ReductionCard should be renamed to ReductionCardType.

Introduce new lookup-resource ReductionCard with query string parameters issuer and identifier.

```json
{
    "reductionCardId": "{{ReductionCard.id}}",
    "reductionCardType": {
      "id" : "{{ReductionCardType.id}}",
      "issuer": "urn:uic:rics:1234",
      "name": "Example Travel Card"
      ...
    }
    "identifier": "1234567890",
    "holderName": "Example Holder Name",
    "expirationDate": "9999-12-31",
    "unit": "MONEY",
    "unitName": null,
    "balanceCurrency": "urn:iso:std:iso:4217:EUR",
    "totalBalance": "100",
    "remainingBalance": "60",
    "regionalConstraint": null,
    "consumptions" : []
}
```

ReductionCardConsumption provides history of consumption.

```
{
    "bookingId" : null,
    "unitsSpent" : 1,
    "spentOn" : "2023-01-01T01:01:01+01:00"
}
```

BookingId is optional.


Extend Offer in resource with array `balanceConsumptions`. This property provides indication how many units will be deduced from the reduction card when the offer will be booked. Below is example of a single `BalanceConsumption`.

```json
{
    "unit" : "MONEY",
    "amount" : 100,
    "currency" : "urn:iso:std:iso:4217:EUR"
}
```

Also note that percentage discount of the reduction card will be provided textually in the ReductionCardType.name. This information is not needed in a machine readable form as the calculation is done be internal system and not the distributor connected via OSDM.

**Comment by ralfbayer-db** [comment]
Discussion at the meeting on 3rd February: split the „ReductionCard“ into various subtypes, i.e.

AbstractTravelAccount
-	MultiRideAccount (Stripes, Trips, Credits, Days etc), has consumption and balance. This includes the multi-day passes like Interrail 5 days of travel out of 20 calender days
-	ReductionCard (e.g. Bahncard 25, 50, Swiss Halbtax, NS Voordeelkaart)
-	TravelPass (e.g. Bahncard 100, Swiss Generalabonnement, and also Weekly Pass for center of Prague)

When a MultiRideAccount is applied to an offer request, it typically results in a zero price offer with the indication of number of “units” which would be spent when the offer is booked
When a ReductionCard is applied, it reduces the price according to the tariff used (e.g. a BC50 reduces a Sparpreis by 25%, and it doesn’t reduce certain PTA prices at all)
When a Travel Pass is applied, it typically reduces the price of the part that is covered by the pass by 100%, and you only pay for the rest (e.g. BC100 on a trip from Munich to Paris – you only pay for the French part of the route)

**Comment by jspetrak** [comment]
Q: move birthDate from Passenger to PersonDetail?

**Comment by ralfbayer-db** [comment]
Hi, I can't see where Passenger or PersonDetail come into play with these items. And frankly, I would leave all the passenger related structures as is and if we need one of these here simply reference them.

**Comment by jspetrak** [comment]
@ralfbayer-db @Linus-Turnit I was just working on this with Andreas and giving it more polish. Will explain tomorrow at the call, and we can still rethink that.

**Comment by schlpbch** [comment]
@ralfbayer-db and @jspetrak

**Comment by schlpbch** [comment]
@ralfbayer-db and @jspetrak: Thanks for your work it's part of OSDM 3.0 now.
