### ISSUE TITLE
More informational texts to be included for Products and Fulfillment Parts

### ISSUE THREAD

**Issue by ralfbayer-db** [UnionInternationalCheminsdeFer/OSDM#331]
[DescriptiveText.txt](https://github.com/UnionInternationalCheminsdeFer/OSDM/files/11329452/DescriptiveText.txt)

Add new "Descriptive Text" array which contains customer-visible additional informational texts, and reference it from products (where it will show texts with addtional information, e.g. "Lounge access included in first class ticket"), and from fulfillment parts (where it will contain the small print which would be included on the PDF ticket, e.g. "Need to show official ID with personalized ticket").

The new object is referenced from Product and from FulfillmentParts. See attached textfile with the relevant YAML snippets.

**Comment by schlpbch** [comment]
Addressed in 3.0.2.pre
