### ISSUE TITLE
Include the effective passenger type in offers and bookings

### ISSUE THREAD

**Issue by ralfbayer-db** [UnionInternationalCheminsdeFer/OSDM#332]
Introduce new object "AppliedPassengerType" which shows which passenger type has been applied for which part of the trip.

This is referenced from abstract offer parts and from abstract booking parts.

See attached yaml snippet.
[AppliedPassengerType.txt](https://github.com/UnionInternationalCheminsdeFer/OSDM/files/11329526/AppliedPassengerType.txt)

**Comment by schlpbch** [comment]
added to 3.0.2 pre.
