### ISSUE TITLE
I-72 Fulfillment options retrieve and override

### ISSUE THREAD

**Issue by ralfbayer-db** [UnionInternationalCheminsdeFer/OSDM#334]
[I72_Fulfillment_Options.txt](https://github.com/UnionInternationalCheminsdeFer/OSDM/files/11444467/I72_Fulfillment_Options.txt)

To retrieve the available options for a particular fulfillment, a new endpoint GET /fulfillments/{id}/options is suggested.

To use the options, new parameters are added to the GET /fulfillments/{id}

See attached.

Possible extensions:
- add another attribute to Fulfillment: fulfillmentOptions, type is FulfillmentOptions (as returned by get .../options above).
- add the request parameters also to the POST /bookings/{}/fulfillments
- deprecate the requested fulfillment options from the booking patch request.

**Comment by jspetrak** [comment]
New Fulfillment Media Type "SMS" would allow to trigger sending a SMS message with either ticket control data or link to obtain the fulfillments.

Patching the booking with adding the SMS media type would trigger not only to issue documents like PDF, but also to send the message.

**Comment by CGantert345** [comment]
SMS added to the code list
