### ISSUE TITLE
I‐94 Capability to handle split seat reservations on a leg

### ISSUE THREAD

**Issue by Linus-Turnit** [UnionInternationalCheminsdeFer/OSDM#356]
There is a need to make it possible to give the passenger place reservations on different parts of a leg.

Use case is: The train is fully booked between leg (A - C). But there is seats available between A-B and B-C. The passenger is OK with the need of changing place at stop B.

To present this in reservation we need a change. Suggested solution could be (TBD).

![image](https://github.com/UnionInternationalCheminsdeFer/OSDM/assets/122451962/121e48d9-8201-4f5c-8b5f-54cbbfad8c1c)

**Comment by CGantert345** [comment]
Would it be an option to provide multiple reservation offers to handle this case. This would not require any changes in the messages and the handling would follow the standard flow. It would make the split also transparent for the customer at offer level so he could select another trip or offer.

**Comment by Linus-Turnit** [comment]
Good thinking!
That could work. Two reservations has tripCoverage with different coveredSections for the same startLegId and endLegId
***@***.***

//Linus

**Comment by Linus-Turnit** [comment]
After more thinking. It might not be that good.

To have two reservations will give problems with the pricing. You are not supposed to pay for two places at splitting the reservation. With the fist suggested solution that problem is out of scope when the reservation part is in one record.

//Linus


From: Linus Johansson
Sent: Tuesday, October 17, 2023 8:25 AM
To: UnionInternationalCheminsdeFer/OSDM ***@***.***>; UnionInternationalCheminsdeFer/OSDM ***@***.***>
Cc: Author ***@***.***>
Subject: RE: [UnionInternationalCheminsdeFer/OSDM] I‐94 Capability to handle split seat reservations on a leg (Issue #356)

Good thinking!
That could work. Two reservations has tripCoverage with different coveredSections for the same startLegId and endLegId

***@***.***

//Linus

**Comment by jspetrak** [comment]
- [ ] @Linus-Turnit You could have a dedicated TYPE=RESERVATION product for splitted reservation and basically calculate the price as fraction of total of price for one? Other operators may support the feature but without the discount...

**Comment by CGantert345** [comment]
Hello Linus,

the pricing for reservations is not on the individual reservation but is modelled as a fee linked to one or more reservations. So pricing is not a problem (e.g. at DB all reservations of a trip are linked to one fee).

Best regards
Clemens

Von: Linus-Turnit ***@***.***>
Gesendet: Dienstag, 17. Oktober 2023 15:32
An: UnionInternationalCheminsdeFer/OSDM ***@***.***>
Cc: Clemens Gantert ***@***.***>; Comment ***@***.***>
Betreff: Re: [UnionInternationalCheminsdeFer/OSDM] I‐94 Capability to handle split seat reservations on a leg (Issue #356)

After more thinking. It might not be that good.

To have two reservations will give problems with the pricing. You are not supposed to pay for two places at splitting the reservation. With the fist suggested solution that problem is out of scope when the reservation part is in one record.

//Linus


From: Linus Johansson
Sent: Tuesday, October 17, 2023 8:25 AM
To: UnionInternationalCheminsdeFer/OSDM ***@***.***<mailto:***@***.***>>; UnionInternationalCheminsdeFer/OSDM ***@***.***<mailto:***@***.***>>
Cc: Author ***@***.***<mailto:***@***.***>>
Subject: RE: [UnionInternationalCheminsdeFer/OSDM] I‐94 Capability to handle split seat reservations on a leg (Issue #356)

Good thinking!
That could work. Two reservations has tripCoverage with different coveredSections for the same startLegId and endLegId

***@***.***<mailto:***@***.***>

//Linus

**Comment by CGantert345** [comment]
> There is a need to make it possible to give the passenger place reservations on different parts of a leg.
> 
> Use case is: The train is fully booked between leg (A - C). But there is seats available between A-B and B-C. The passenger is OK with the need of changing place at stop B.
> 
> To present this in reservation we need a change. Suggested solution could be (TBD).
> 
> ![image](https://user-images.githubusercontent.com/122451962/274847560-121e48d9-8201-4f5c-8b5f-54cbbfad8c1c.png)

--> additional element in the offer search required: acceptedSpecialFeatures with vaule SPLIT_RESERVATION

**Comment by Linus-Turnit** [comment]
Turnit doesn't think it is feasible to manage split-reservations by having several reservations covering different sections of a leg. 

The reservation-object describes a logical and physical reservation with product descriptions, after sales rules, price, places and so on. It is only the placeAllocation that describes the physical part, all other parts are logical related.  

There is already a possibility to have a list of placeAllocations for a reservation, in specification described to handle bicycle reservation together with the seat. Another use-case is to present a product where next seat is free (actually already a case in Sweden). In that case you get one reservations with two placeAllocations.

For split-reservations there will be two placeAllocations as well with different reservationSection's covering different parts of a leg. 

Our opinion is that this is a small, non required, addon to the placeAllocation object. It is only IMS's with this functionality that will return reservationSection:s and it is only returned if the productTag "SPLIT_RESERVATION" is provided in offer search from the customer. With good comments in the API it can be clear for the consumers when to handle this.

The need for split reservations can be discussed, but the seat reservation algorithm is active at booking time and optimize the reservations at that time. Closer to departure, cancellations will change the situation and suddenly a split-reservation booking is possible. With seat-maps, the algorithm is more out of control as well, even if not all free places are shown as selectable.

For Turnit one new carrier (not in Sweden) has split-booking as a requirement and since we aim to be OSDM-compliant in all our API's this is very important for us.

**Comment by CGantert345** [comment]
Decision:

- Use ProductTag
- Add the split as option, to be applied only in case the product tag is set
- Add a comment that defined this as workaround solution for special cases and describe the already existing solution via multiple reservations in the offer.

**Comment by Linus-Turnit** [comment]
In POST /offers
![image](https://github.com/UnionInternationalCheminsdeFer/OSDM/assets/122451962/fb908e99-1a4e-4a68-a955-62ffff15d92f)


```
    OfferSearchCriteria:
      type: object
      additionalProperties: false
      properties:
        requestedOfferParts:
          type: array
          items:
            $ref: '#/components/schemas/OfferPartType'
        productTags:
          type: array
          items:
            $ref: '#/components/schemas/ProductTag'
          nullable: true
        flexibilities:
          description: |
            Defines the flexibility levels desired of the fares returned.
            This refers to the after sales flexibility levels as defined in IRS-90918-10
          type: array
          items:
            $ref: '#/components/schemas/Flexibility'
        travelClasses:
          description: |
            The classes returned might be different from the requested classes.
          type: array
          items:
            $ref: '#/components/schemas/TravelClass'
        serviceClassTypes:
          description: |
            The classes returned might be different from the requested classes.
          type: array
          items:
            $ref: '#/components/schemas/ServiceClassType'
          maxItems: 4
        offerMode:
          $ref: '#/components/schemas/OfferMode'
        currency:
          $ref: '#/components/schemas/Currency'
        
    ProductTag:
      description: |
        Known values:
        - SPLITED_RESERVATION
          Indicate for the provider that the distributor is prepared to get splitted reservations in the response
      type: string
      x-extensible-enum:
        - SPLITED_RESEVATION
```
GET /booking/{bookingId}
