### ISSUE TITLE
Using second last names

### ISSUE THREAD

**Issue by CGantert345** [UnionInternationalCheminsdeFer/OSDM#357]
Currently multiple last names are handled concatenated in one element **lastName**. 

Proposal:

Adding an optional second last name to have multiple last names in separate fields.

As multiple names are not commonly used in retail systems the solution should have no impact on systems using one name filed in passenger data.

- Option 1: one optional second last name

a retailer is allowed to ignore the second optional name and not provide the name separately
a distributor is allowed to ignore the second optional name and use only the first last name

- Option 2: lastName hold all last names as today and is mandatory

optional element firstLastName holds the first last name and can be ignored
optional element secondLastName holds the second last name and can be ignored

**Comment by jspetrak** [comment]
Copying the findings from the last Teams call. 

https://www.iata.org/contentassets/18a5fdb2dc144d619a8c10dc1472ae80/2010-api-guidelines-final-version-mig-release-date-25-11-2010.pdf (page 26)

IATA PAXLIST (Passenger List Message) uses single field name "Party Name" a allows for multiple inserts in descending priority where only the first one is expected as the "Last Name".

https://www.iata.org/contentassets/18a5fdb2dc144d619a8c10dc1472ae80/pnrgov20xml20implementation20guide2015_1.pdf (page 31)

For a PNR record, Surname has cardinality 0..1.

For air-rail compatibility, passenger last name must be provided with all names concatenated.

More general improvement could be to provide additional optional element `lastNameItemized` or other similar name that would be array of strings, and list surnames in descending order by priority (paternal, maternal, ...)

**Comment by jspetrak** [comment]
Proposals discussed.

```
Current situation

{
  "FirstName": "Jose",
  "LastName" : "Vavra Nebrenska"
}

Option #1

{
  "FirstName": "Jose",
  "LastName" : "Vavra Nebrenska",
  "LastName2" : "Nebrenska"
}

Option #2

{
  "FirstName": "Jose",
  "LastName" : "Vavra Nebrenska",
  "LastName1" : "Vavra",
  "LastName2" : "Nebrenska"
}

Option #3

{
  "FirstName": "Jose",
  "LastName" : "Vavra Nebrenska",
  "LastNamesItemized" : [
    "Vavra",
    "Nebrenska"
  ]
}
```

**Comment by ralfbayer-db** [comment]
Whatever is finally decided, a clear description of all lastname fields needs to be provided.

**Comment by CGantert345** [comment]
Solution agreed with RENFE in branch: https://github.com/UnionInternationalCheminsdeFer/OSDM/tree/adding-support-for-two-last-names

**Comment by CGantert345** [comment]
Rename to firstFamilyName, secondFamilyName
