### ISSUE TITLE
Indicator for overriden aftersales conditions

### ISSUE THREAD

**Issue by stinacarlstedt** [UnionInternationalCheminsdeFer/OSDM#362]
During a disruption (or for other reasons) the aftersales conditions in the original booking can be overriden, so that a NO_FLEX-ticket becomes MID or FULL_FLEX to allow the passenger to reach their final destination. Currently, there is no way to signal to a client that such an override has been activated. We propose an update to the AbstractBookingPart to allow the operator to pass information to the distributor or the end-client around this override.

**Comment by stinacarlstedt** [comment]
Proposed modelling:
<img width="547" alt="image" src="https://github.com/UnionInternationalCheminsdeFer/OSDM/assets/48951735/ef7ce55a-8f1c-4207-ae13-59420d728d38">

**Comment by stinacarlstedt** [comment]
Updates to RefundType and ExchangeableType, to include flag and initial condition. Breaking change from v 3.

**Comment by stinacarlstedt** [comment]
Intermediate solution:
* Leave ExchangeableType and RefundType as they are (string - enum YES, NO, WITH_CONDITION)
* Add an optional parallel structure with AfterSalesOverrideDetails, specifying that the conditions have been overriden and preserving the initial conditions (with additional optional information, such as validity if applicable, description text on the reason for the channels, etc)

<img  alt="image" src="https://github.com/UnionInternationalCheminsdeFer/OSDM/assets/48951735/61bedfe3-0f77-43fd-9aa3-a6fcf5158b9a">

**Comment by stinacarlstedt** [comment]
We should also review whether the term should be AfterSale or AfterSales - we use both currently. Later...

**Comment by ConscritNeuneu** [comment]
I think the correct term is `aftersales` but I'm not native.

**Comment by stinacarlstedt** [comment]
Update proposed to the webhook enum:

<img width="307" alt="image" src="https://github.com/UnionInternationalCheminsdeFer/OSDM/assets/48951735/cf188eec-7664-49f4-b5cc-4ac4c289ce75">

**Comment by CGantert345** [comment]
I have added a slightly different proposal by adding GrantedReductionAmounts.  It allows to show reductons that are not associated with individual passengers e.g. group reductions.

**Comment by jspetrak** [comment]
@CGantert345 to draft PR
