### ISSUE TITLE
Third Party Accounting Reference

### ISSUE THREAD

**Issue by CGantert345** [UnionInternationalCheminsdeFer/OSDM#393]
In some cases the accounting for a bookedOfferPart is not done by the provider of the API but by the provider of the transport service of the booking part. E.g. 
- SNCF provides a combined booking with Eurostar, but Eurostar is billing this directly.  

To allow a validation of the billing the bookedOfferPart needs to include a reference to the accounting company  and a list of accountingIds that will be used by the accounting company in the accounting data to reference the bookedOfferPart. A list is needed as some accounting systems further detail the bookedOfferPart.

**Comment by ralfbayer-db** [comment]
- rename the fields of the AccountingRef structure (accountingCompany --> company, accountingIds --> ids) and add the accountingRef to the Fee object. Clemens provides a patch.
