### ISSUE TITLE
Start value for indexes in routes (stop numbers) should not be mandatory 1

### ISSUE THREAD

**Issue by ralfbayer-db** [UnionInternationalCheminsdeFer/OSDM#404]
Some journey planners (notably HAFAS) numbers the stops starting at 0. The standard should be more flexible here

**Comment by CGantert345** [comment]
not an issue

**Comment by ralfbayer-db** [comment]
This is still an issue, The relevant places where the index is in the API are:

- TimedLeg.intermediates[].status.order (the order field starts with 1) and
- TimedLeg.attributes[].LegAttribute.fromStopNumber / toStopNumber (both are said to start with 1)

These need to be matched in order to display information texts which only apply to a subset of the leg (e.g. restaurant closed during part of the leg).

HAFAS starts these indexes with 0.

**Comment by ralfbayer-db** [comment]
Change the minimum to 0, Ralf will provide a pull request.
