### ISSUE TITLE
Passenger Types and UIC 918.9

### ISSUE THREAD

**Issue by ralfbayer-db** [UnionInternationalCheminsdeFer/OSDM#409]
How do the PassengerTypes specified by OSDM match with the PassengerTypes according to UIC918.9?

We should align them as much as possible.

For reference, these are the passenger types that can occur in a barcorde according to UIC 918.9:

- adult
- senior
- child
- youth
- dog
- bicycle
- freeAddonPassenger
- freeAddonChild

**Comment by CGantert345** [comment]
Add a column to the code table documenting the related 918-9 codes.  TODO CG
