### ISSUE TITLE
Included Reservations vs. Reservations link

### ISSUE THREAD

**Issue by ralfbayer-db** [UnionInternationalCheminsdeFer/OSDM#410]
Under the admissionOfferParts there is an element called includedReservations, what is the correct meaning behind this since there is a second structure underneath admissionOfferParts.reservations that creates a link to a reservationOfferPart. What is the difference? Will includedReservation only containt "Inklusivreservierung" and mandatory and optional reservations will be listed under reservations? We would prefer one place for all reservation references.

There is also the flag "isReservationRequired", how exactly does this interact with the reservation groups / min vs. max items?

**Comment by CGantert345** [comment]
isReservationRequired is used with fares where the the fare and the erservation might be in separate systems.

**Comment by CGantert345** [comment]
Ralf & Roland to provide documentation

**Comment by jspetrak** [comment]
Proposal:

Get rid of AdmissionOfferPart.includedReservations, use AdmissionOfferPart.reservations.

Add ReservationRelation.included boolean property instead.

**Comment by KlausKovar** [comment]
Maybe we dont need this flag - in case of an IRT offer the productcode of the admissionOfferPart and the corresponding reservationOfferPart should always be the same (since it is the same tariff). If it is necessary to recognize an offer with integrated reservations this should be sufficient.

**Comment by ralfbayer-db** [comment]
Let us make it explicit instead of "compare the product codes and see whether they are the same" logic.
