### ISSUE TITLE
ReductionCardType (appliedReductionCardTypes) doesn't hold information of cardNumber and cardType	

### ISSUE THREAD

**Issue by Linus-Turnit** [UnionInternationalCheminsdeFer/OSDM#420]
Information in appliedReductionCardTypes is not complete.
Applied card number and card type is not possible to return in offers and bookings responses.

Can we add them as optional to ReductionCardType or will that make GET /reduction-cards response to "dirty"?

**Comment by ralfbayer-db** [comment]
Additional question from DB: the GET /reduction-cards does not return the type of card, but this is needed on input for the card types when they are entered into an offer search. Do we assume that everything returned by GET /reduction-cards is of type reduction card? If this is the case, how can a consumer obtain a list of other reduction/card types from the provider, i.e. do we need more master data endpoints?

**Comment by CGantert345** [comment]
deprecate appliedReductionCardTypes
add appliedReductions as CardReference
