### ISSUE TITLE
Questions mit `PlaceAvailabilityResponse`

### ISSUE THREAD

**Issue by schlpbch** [UnionInternationalCheminsdeFer/OSDM#431]
We have two 

- Should `Compartement.number` be mandatory?
- `isSelectable` needed in this data structure?

![PlaceAvailabilityResponse](https://github.com/UnionInternationalCheminsdeFer/OSDM/assets/18540761/d219668c-07f8-4cc6-a919-729a9ea4cad8)

**Comment by CGantert345** [comment]
Compartment.number should be optional. In case of open space coaches it has no meaning.

**Comment by CGantert345** [comment]
isSelectable indicates that the entire compartment is selectable, e.g. in night trains fo offers on complete compartments.

**Comment by schlpbch** [comment]
duplicate
