### ISSUE TITLE
ReturnSearchParameters in tripSpecification is missing

### ISSUE THREAD

**Issue by Linus-Turnit** [UnionInternationalCheminsdeFer/OSDM#434]
When using tripSearchCriteria there is a possibility to inform the provider that this offer search is a outbound offer search for a round-trip offer by using tripSearchCriteria.returnSearchParameters.inwardReturnDate.

Structure ReturnSearchParameters is not available in tripSpecification. Suggestion is to add it (optional) on root-level.

It would be good to add outwardTripDate in the ReturnSearchParameter as well, to give the inward offer calculator the notice of how long the stay at departure is.

![image](https://github.com/UnionInternationalCheminsdeFer/OSDM/assets/122451962/96c28488-cc76-4354-a88d-e7e838d6c2d5)

**Comment by CGantert345** [comment]
Add  returnSearchParameters to tripSpecification (optional)

**Comment by nixxus1030** [comment]
I thought we agreed returnparameters are only relevant for offers ? (the fact a trip is part of a return may affect fares returned, not the trains realizing the trip)
