### ISSUE TITLE
Remove "houseNumber" from addresses

### ISSUE THREAD

**Issue by ralfbayer-db** [UnionInternationalCheminsdeFer/OSDM#435]
Adresses in OSDM (both "place addresses" and "people addresses" have a separate field for the "houseNumber".  We don't have the house number in a separate field and have it in the "street" field.

We suggest deprecating and subsequently removing the "houseNumber" field with the following rationale:

- many systems do not store the houseNumber separately, for them it is difficult to separate out the houseNumber

- the place of the house number within the street address varies between countries - e.g. in german speaking countries the house number is usually a suffix to the street (e.g. Europaallee 78), while in the UK it is typically a prefix (e.g. 4 Willow Court). Therefore, constructing a correct address line from separate fields is not easy - the system would need to know and consider the convention for all supported countries

**Comment by jspetrak** [comment]
One other reason to not separate this information is existence of multiple "house numbers" simultaneously for single given house. E.g. in Czechia there is "číslo popisné" (description number, Konskriptionsnummer), "číslo orientační" (orientation number, Hausnummer) and you are supposed to use both and in given order: desc. number slash orien. number.

**Comment by ralfbayer-db** [comment]
Keep houseNumber as separate field, but add patch stating that the street may contain the house number in which case that must be empty. Ralf to provide a patch.
