### ISSUE TITLE
Clarification required: Authorization/Authentication tokens

### ISSUE THREAD

**Issue by ralfbayer-db** [UnionInternationalCheminsdeFer/OSDM#436]
Regarding the OAUTH Tokens used for authentication and authorisation, we require some clarifications

- The OSDM Provider's IDM will provide pairs of access token/refresh token
- They will be JWTs (JSON Web Tokens) (at least the access token)
- The token endpoint will return the expiry time of the access token in [the standard way](https://datatracker.ietf.org/doc/html/rfc6749#section-5.1)
- An OSDM Consumer can request and use multiple sets of access/refresh tokens for the same IDM account in parallel (to support distributed/parallelized consuming services). In particular, requesting a new token pair from the IDM does NOT invalidate previously issued tokens which have not yet expired

**Comment by CGantert345** [comment]
might be covered by JWT - to be checked

**Comment by schlpbch** [comment]
Addressed in documentation.
