### ISSUE TITLE
Refund complete booking

### ISSUE THREAD

**Issue by ralfbayer-db** [UnionInternationalCheminsdeFer/OSDM#446]
In case of errors we would like to refund a complete booking (typically with override codes of either TECHNICAL_ERROR or PAYMENT_ERROR). In this case it would be helpful to be able to ask for a refund offer without having to specifiy fulfillmentIDs.

Proposal:

- either make fulfillmentIDs optional in the POST .../refundOffers (with the semantics of asking to refund the complete booking), or

- create another endpoint POST .../refundOfferCompleteBooking, with the same semantics, with the same signature as the original refundOffers request, just without the fulfillmentIDs.

**Comment by jspetrak** [comment]
New endpoint getting just bookingId, overruleCode and refundData, no second step needed to confirm the refund. @ralfbayer-db to create a patch
