### ISSUE TITLE
Limit available mime types for fulfillment documents

### ISSUE THREAD

**Issue by ralfbayer-db** [UnionInternationalCheminsdeFer/OSDM#448]
Can we limit the allowable mime types for fulfillment documents (FulfillmentDocument.format) to 

- application/pdf
- image/jpeg
- image/png
- text/html

**Comment by jspetrak** [comment]
Can also be
- wallet files
- calendar files

**Comment by jspetrak** [comment]
application.vnd.pkpass

google wallet doesn't have a mime type, only download link

**Comment by CGantert345** [comment]
TODO: Finalize a change without google wallet for the time being.  --> Joseph

**Comment by jspetrak** [comment]
> application/vnd.pkpass

The correct type is `application/vnd.apple.pkpasses` according to the specification https://developer.apple.com/documentation/walletpasses/distributing_and_updating_a_pass

**Comment by jspetrak** [comment]
#510 was created because one of document objects has format completely optional. Would be breaking to enforce it now.
