### ISSUE TITLE
Distinguish between "Place Address" and "People/Company Address"

### ISSUE THREAD

**Issue by ralfbayer-db** [UnionInternationalCheminsdeFer/OSDM#449]
The current Address type in OSDM contains the "Place"-Attributes, which makes an ID mandatory. While this is necessary for Place Addresses used in trip searches, it is irrelevant for addresses used in the booking structures (Purchaser, Passenger.PersonDetail, CompanyDetail).

We propose:
- rename the current Address structure to PlaceAddress, and use it within trip search and trip result structures
- create a new Address structure which does not inherit from Place and use it in the booking-related structures

As this will be a breaking change, for the meantime document that the ID within the address is purely fictional for addresses used for people or companies.

**Comment by ralfbayer-db** [comment]
- add a new Address Object (PostalAddress?) and add this to PersonDetail and CompanyDetail
- deprecate the old address attribute in these objects
- wait and pray for OSDM 4 to clean up this mess...

**Comment by CGantert345** [comment]
TODO: prepare patch --> Ralf
