### ISSUE TITLE
Trips are missing in ExchangeOperationResponse

### ISSUE THREAD

**Issue by Linus-Turnit** [UnionInternationalCheminsdeFer/OSDM#454]
In exchangeOperationResponse trips are missing but the offers has mandatory tripReferences in tripCoverage.

Looks like a bug to me.

![image](https://github.com/UnionInternationalCheminsdeFer/OSDM/assets/122451962/f8d35d9e-0406-42b2-97c3-49c837765ca9)

**Comment by Linus-Turnit** [comment]
This is a bug that would be good to have fixed in 3.2. I can't really see any objections to this

**Comment by jspetrak** [comment]
Agreed. @Linus-Turnit will you provide a PR for that?

**Comment by Linus-Turnit** [comment]
Hmm. I am not so confidence doing that. Hope you can help me. It is the trips array below that is needed

    ExchangeOperation:
      type: object
      additionalProperties: false
      required:
        - id
      properties:
        id:
          type: string
          nullable: false
        status:
          $ref: '#/components/schemas/ExchangeStatus'
        exchangeOffers:
          type: array
          items:
            $ref: '#/components/schemas/ExchangeOffer'
        ticketTimeLimit:
          type: string
          format: date-time
          nullable: true
        fulfillmentType:
          $ref: '#/components/schemas/FulfillmentType'
        fulfillments:
          type: array
          items:
            $ref: '#/components/schemas/Fulfillment'
        issuedVouchers:
          type: array
          items:
            $ref: '#/components/schemas/VoucherInformation'
        trips:
          type: array
          items:
            $ref: '#/components/schemas/Trip'
