### ISSUE TITLE
Filter for transport mode per section defined by vias

### ISSUE THREAD

**Issue by schlpbch** [UnionInternationalCheminsdeFer/OSDM#465]
In Switzerland, people want to be able to choose the bus for the first, the train for the second and a boat for the last leg.

Do others have this need?

**Comment by ralfbayer-db** [comment]
Yes, we initially didn't have this ability with the release of Vendo/MOVAS last year and this was in the top 3 of the complaint feedbacks. It is now again available with our app and website.

**Comment by ralfbayer-db** [comment]
The way we support it is that in the trip search parameters there needs to be a via, and you can specifiy the transport mode per section defined by the vias (so A-D via B and C, you can specificy the transport mode for the A-B, B-C, C-D sections). Each section can then, obviously, consist of one or several legs.

**Comment by ralfbayer-db** [comment]
The way HAFAS implements this in the API is to have the transport mode filter as an attribute at the via, meaning that this affects the section after this via - and (suprisingly, we shouldn't copy this) the global transport mode filter applies to the first leg (between origin and 1st via).

**Comment by ralfbayer-db** [comment]
Ralf will provide a patch.
