### ISSUE TITLE
On-hold missing delete operation to cancel the on-hold request

### ISSUE THREAD

**Issue by rolandkla** [UnionInternationalCheminsdeFer/OSDM#469]
An on-hold can be requested using `POST /bookings/{bookingId}/on-hold-offer` and can be confirmed using a `PATCH`.
There are 3 omissions in the on-hold flow:
- a pending on-hold cannot be cancelled since a `DELETE` operation is missing. The client has to wait out the TTL
  - my recommendation is to introduce a `DELETE` on-hold-offer to cancel the pending on-hold
- the on-hold flow is resource based, while an on-hold request is by definition booking based since it does not allow any context as input. And the details of an onHoldOffer cannot be patch, making referencing to such an offer unneeded. Therefore having an `onHoldOfferId` is unnecessary, since there cannot be multiple to be confirmed
  - my recommendation is to remove the `onHoldOfferId` from the `onHoldOffer` and in the `PATCH` request, similar to the purchaser definition and resources
- the `onHoldOffer` is not returned in the booking response, unclear for clients to know if there is a pending on-hold when fetching a booking

**Comment by jspetrak** [comment]
- Add DELETE 
- Add OnHolderOffer to Booking
- Deprecate PATCH /bookings/{bookingId}/on-hold-offer/{onHoldOfferId} (and remove in 4.0) onHoldOfferId, create PATCH /bookings/{bookingId}/on-hold-offer

**Comment by CGantert345** [comment]
TODO patch Roland
