### ISSUE TITLE
Use sales flow endpoints to add non-trip and trip offers to a confirmed booking

### ISSUE THREAD

**Issue by Linus-Turnit** [UnionInternationalCheminsdeFer/OSDM#470]
This is a discussion regarding if it would be possible to use sales endpoints currently limited to not confirmed bookings to also be possible to use on a confirmed booking to add new offers/offerParts to the booking.
The end-points them selves is probably good to use in a confirmed state as well, but documentations says that they shall be used in a preBooking state only.

End-points to discuss is:
**Bookings**
- PATCH /bookings/{bookingId}
- DELETE /bookings/{bookingId} is not in scope when confirmed.

**BookedOffers**
- POST /bookings/{bookingId}/booked-offers (Add new offers to an existing confirmed booking)
- DELETE /bookings/{bookingId}/booked-offers/{offerId} (as long as offer is not confirmed, If confirmed use refund)

**BookingParts**
- POST /bookings/{bookingId}/booked-offers/{bookedOfferId}/reservations
- DELETE /bookings/{bookingId}/booked-offers/{bookedOfferId}/reservations/{reservationId} (as long as offerPart is not confirmed, If confirmed use refund)
- POST /bookings/{bookingId}/booked-offers/{bookedOfferId}/ancillaries
- DELETE /bookings/{bookingId}/booked-offers/{bookedOfferId}/ancillaries/{ancillaryId} (as long as offerPart is not confirmed, If confirmed use refund)
- DELETE /bookings/{bookingId}/booked-offers/{bookedOfferId}/admissions/{admissionId} (as long as offerPart is not confirmed, If confirmed use refund)

**Passengers**
- PATCH /bookings/{bookingId}/passengers/{passengerId} (On not confirmed offers)

**Purchaser**
-  PATCH/bookings/{bookingId}/purchaser (This one is tricky since part is already confirmed)

**Comment by CGantert345** [comment]
Discussion: - this should not be a recommended / required flow

Adding reservations / ancillaries could be done via exchange. Is simpler alternative needed? Yes

To Be Continued

**Comment by CGantert345** [comment]
TODO: change documentation:
 - a provider can decide to allow additional admissions, reservations or ancillaries on an confirmed booking.
 
TODO: change documentation --> Clemens
