### ISSUE TITLE
Clarification on stopBehaviour.REAL_BOARDING_ALIGHTING enum value

### ISSUE THREAD

**Issue by harrybaker-srt** [UnionInternationalCheminsdeFer/OSDM#474]
Hello,

I just have a question on the field mentioned in the title. I'm currently implementing intermediate stops on TimedLegs and was wondering if this was the intended parameter choice over the field TripContentFiller.IncludeIntermediateStops available on the OJP spec.

https://github.com/UnionInternationalCheminsdeFer/OSDM/blob/27f9e64b518bb5c0d469e3d37d3c51728a39eaf1/specification/v3.2/OSDM-online-api-v3.2.0.yml#L408

Thanks,
Harry

**Comment by jspetrak** [comment]
Note: rail / bus border points to indicate border crossing are not virtual points. Virtual points are used for international fares.

Yes, it maps to `TripContentFiller.IncludeIntermediateStops`.

**Comment by schlpbch** [comment]
No reaction to proposed answer. Please reach out to us in case more clarification is needed.

**Comment by harrybaker-srt** [comment]
Sorry for the late response, this answers my question, many thanks.
