### ISSUE TITLE
RFC 7807 superseded by RFC 9547 for HTTP Problem Detail

### ISSUE THREAD

**Issue by schlpbch** [UnionInternationalCheminsdeFer/OSDM#486]
In the swagger API documentation file (OSDM-online-api-v3.0.3.yml) is there a reference to RFC 7807. Should this be replaced with reference to  [RFC 9457: Problem Details for HTTP APIs](https://datatracker.ietf.org/doc/html/rfc9457)?

Delta is defined here:
https://datatracker.ietf.org/doc/html/rfc9457#name-changes-from-rfc-7807

**Comment by jspetrak** [comment]
@schlpbch A pull request will be created when we finish the discussion on error handling and gather all necessary changes to API and documentation.

**Comment by jspetrak** [comment]
Josef to review if the new RFC is BC. If so, update the docs.

**Comment by jspetrak** [comment]
From #361

> RFC 7807 is deprecated in favor of RFC 9457.

> https://www.rfc-editor.org/rfc/rfc9457.html

> https://blog.frankel.ch/problem-details-http-apis/
