### ISSUE TITLE
Relation between fulfilment and leg within a through fare

### ISSUE THREAD

**Issue by rolandkla** [UnionInternationalCheminsdeFer/OSDM#489]
A fulfilment has a relation to one or more bookingParts and a bookingPart is for a trip with one or more legs. There is however no relation between a fulfilment and leg

In cases where a bookingPart covers multiple legs, for instance a through fare, and each leg has its own fulfilment it is not possible to link that directly to a leg.

Example:
```
- trips[]
  - id: 1
  - legs[]
    - timedLeg: A > B
    - timedLeg: B > C

- bookedOffer
  - admission
    - id: abc  
    - tripCoverage
       - coveredTripId: 1
 
- fulfillments[]
  - fulfilment
    - id: 1
    - bookingParts[abc]
   - fulfilment
    - id: 2
    - bookingParts[abc]
```

How can we link that fulfilment 1 is for leg A > B and fulfilment 2 is for B > C?

Especially with through fares of different operators this can be confusion or even cause settlement issues.

**Comment by ralfbayer-db** [comment]
Problem: the same through fare links to multiple fulfillments (e.g. one per leg) as multiple operators are giving out their own fulfillments. They each have individual control numbers and operator codes.

This means that multiple fulfillments point to the same BookedOfferPart, but the model doesn't have a way to distinguish them.

**Comment by stinacarlstedt** [comment]
Suggest one of these to model this link. Most simply, add a string-array to the fulfillment element detailing which legs, as provided in the trip element of the booking, are affected by the fulfillment.
![image](https://github.com/UnionInternationalCheminsdeFer/OSDM/assets/48951735/2da0047b-67a3-4d26-abb7-92d76f4dc3ca)

Alternately, to more closely mirror the way the booking parts are handled, same principle but using a LegReference element to detail the affected leg. This would allow for extending the amount of information provided without breaking the schema later:
![image](https://github.com/UnionInternationalCheminsdeFer/OSDM/assets/48951735/9aa1adfa-5584-4f09-9563-c7903fc3cab1)

Finally, to create a more robust link between the trip and the fulfillment, a TripCoverage element as previously defined could be added to the fulfillment outright. 
![image](https://github.com/UnionInternationalCheminsdeFer/OSDM/assets/48951735/08841e4c-3981-4f2f-9481-f5bd67bb4a07)

**Comment by CGantert345** [comment]
TODO patch for next meeting --> Roland

**Comment by rolandkla** [comment]
https://github.com/UnionInternationalCheminsdeFer/OSDM/tree/feature/489

**Comment by jspetrak** [comment]
@rolandkla Could you also create the merge request? If I create one, I can't approve it being creator of the MR.

**Comment by ralfbayer-db** [comment]
Unfortunately DB cannot support multiple fulfillments per Admission.

**Comment by CGantert345** [comment]
Examples for the cases are needed by DB

**Comment by stinacarlstedt** [comment]
1. Through-fare with the same operator on both (all) legs will give one admission but one fulfillment per leg. (SJ)
