### ISSUE TITLE
Improve OAuth documentation on backend to backend OAuth

### ISSUE THREAD

**Issue by jspetrak** [UnionInternationalCheminsdeFer/OSDM#491]

**Comment by ralfbayer-db** [comment]
The draft documentation can be viewed here: https://github.com/UnionInternationalCheminsdeFer/OSDM/blob/491-improve-oauth-documentation-on-backend-to-backend-oauth/spec/authentication.md

**Comment by ralfbayer-db** [comment]
Note that the draft has been merged into the main documentation branch, hence it can be viewed at https://osdm.io/spec/authentication/

**Comment by schlpbch** [comment]
Job done, thank you Josef!
