### ISSUE TITLE
BookingParts and Fares changed by the provider due to reacommodation or cancelled trains are difficult to detect.

### ISSUE THREAD

**Issue by CGantert345** [UnionInternationalCheminsdeFer/OSDM#494]
In case of an reaccomodation or a cancelled train the provider will modify a booking part or fare and inform the consumer via a webhook. The message includes the booking id. It is difficult to detect which part was changed or exchanged due to the reaccomodation or train cancellation.

**Comment by CGantert345** [comment]
In case of an reaccomodation or a cancelled train the provider will modify a booking part or fare and inform the consumer via a webhook. The message includes the booking id. It is difficult to detect which part was changed or exchanged due to the reaccomodation or train cancellation.

**Comment by jspetrak** [comment]
List frequent cases of change.
Make webooh event more detailed to help retailers/distributors understand the change.

**Comment by stinacarlstedt** [comment]
Might be useful to include not only a bookingID but also a (list of) fulfilmentId for this and other "update" cases.

**Comment by CGantert345** [comment]
Add simple optional lists:
- affectedFullfilmentIds
- affectedBookedOfferPartIds

TODO pull request Clemens
