### ISSUE TITLE
Specification for earlier/later trips?

### ISSUE THREAD

**Issue by MaximeAnsquer** [UnionInternationalCheminsdeFer/OSDM#505]
Hello,

I am wondering if OSDM has any recommandation for a specification of a "earlier/later trips" feature: given a trip collection, find trips with earlier (or later) departure dates.

Thanks!

**Comment by CGantert345** [comment]
OSDM uses pagination: https://osdm.io/spec/pagination/

**Comment by MaximeAnsquer** [comment]
Perfect, thanks for the quick response.
