### ISSUE TITLE
Information about limited availability in the warning structure 

### ISSUE THREAD

**Issue by KlausKovar** [UnionInternationalCheminsdeFer/OSDM#507]
In case that no offer can be created (IRT based or reservation offer) for a specific train a warning with additonal information should be returned.

Eg:
1) request for an "IRT train": in case that the IRT train is sold out the offers[]-request returns an empty offers list with a warning that contains the sold out information for this train.
2) request for a NRT based regional train and an IRT train: in case that the IRT train is sold out the offers[]-request returns an offers list with offers for the regional train together with a warning containing the sold out information for the IRT train.
3) request for a NRT based offer on a trip that consists of more than one reservable day trains. In case that one or more trains are sold out the offers[]-request returns a list of NRT based offers together with warnings containing the sold out information for the train (so no reservation offer is possible)

Information in the warning should distinguish:
- "sold out" or "no availabilty": all places on the train are booked or permanently blocked
- "temporarily not bookable": train is temporarily closed for reservation (but will be opened again)
- limited availability": not all persons or transportables from the request can be transported
- ...

In addition to the attributes "type", "title" and "detail" the warning structure should contain:
- tripId
- leg id (so the train can be clearly identified)
- some code or status
- ` "warnings": [
    {
      "type": "/problems/warnings/availability/limited-availability",
      "title": "Train has limited availability.",
      "detail": "All spots are booked or permanently blocked",
      "tripId": "conn01234",
      "legId": 1234,
      "code": "noAvailability"
    }
], [...]`

**Comment by CGantert345** [comment]
Additional elements in Warning:

   - use generic pointer to resources related to the warning
   - Documentation:  
              Error code --> relevant pointers


Warning Codes:
        Code list in chapter error handling to be extended

+
       SERVICE_NOT_BOOKABLE_TEMPORARILY              (not bookable for some days due to replaning)
       SERVICE_NOT_BOOKABLE_FOR_A_SHORT_TIME    (not bookable for a few minutes due to short term data management)
       SERVICE_NOT_BOOKABLE_PERMANENTLY            (cancelled train)
       SERVICE_SOULD_OUT
       SERVICE_NOT_ENOUGH_PLACES_FOR_ALL_PASSENGERS
       SERVICE_NOT_YET_AVAILABLE_FOR_BOOKING


Link to the code list needed in the schema


To be discussed in the "error group"

**Comment by ralfbayer-db** [comment]
Relates to #390

**Comment by CGantert345** [comment]
Wording:

 SERVICE_TEMPORARILY_NOT_AVAILABLE              (not bookable for some days due to replaning)
 SERVICE_NOT_AVAILABLE_FOR_A_SHORT_TIME    (not bookable for a few minutes due to short term data management)
 SERVICE_NOT_ABAILABLE_PERMANENTLY            (cancelled train)
 SERVICE_NO_AVAILABILITY                              
 SERVICE_INSUFICCIENT_AVAILABILITY
 SERVICE_NOT_YET_AVAILABLE
