### ISSUE TITLE
Suggestion - Provide scenarios around time-to-live / confirmableUntil

### ISSUE THREAD

**Issue by stinacarlstedt** [UnionInternationalCheminsdeFer/OSDM#516]
The underlying systems' solutions for handling TTL for pre-booked bookings will have a big impact on the implementation. It would be good to set a pattern as best-practice for this. This may be a challenge, as it is not simply a matter for the API but also the implementation in the underlying system. But without a untified handling of this multi-inventory will be challenging.

**Comment by CGantert345** [comment]
Two behaviours:          update the TTL with patches or keeping the TTL as initially set

booking --> confirmationTimeLimit                 
bookedOfferPart --> confirmableUntil -->  to be deprecated

in case of multiple providers use the minimum of all providers bookings->confirmationTimeLimit


TODO: patch  Clemens
