### ISSUE TITLE
Gap?  - synchoronization between enums/x-enums in the yaml and the documentation.

### ISSUE THREAD

**Issue by stinacarlstedt** [UnionInternationalCheminsdeFer/OSDM#518]
Where practical, it would be very useful to have the standard codes present in the yaml. Perhaps the documentation should only include these where there is an added dimension, for instance with placeProperties vs placePreferences.

**Comment by CGantert345** [comment]
The master is the codelist, as schmas are not changed when new codes apear.

TODO: add a comment to each extensible enum indicating that the values are examples only and a link to the code list in the documentation.    --> Clemens
