### ISSUE TITLE
Suggestion - determine the usage of refundAmount in a booking

### ISSUE THREAD

**Issue by stinacarlstedt** [UnionInternationalCheminsdeFer/OSDM#519]
There is ambiguity whether the the refundAmount provided should contain the value that has been refunded, or the remainder which can be refunded. As there is the potential for chosing different interpretations, it would be good with a decision.

**Comment by CGantert345** [comment]
refundAmount is the amount refunded.

TODO: add comment in abstractBookingPart on refundAmount --> Clemens
