### ISSUE TITLE
admissionOfferParts is not a list in the exchange-offers exchangeOffer response

### ISSUE THREAD

**Issue by rolandkla** [UnionInternationalCheminsdeFer/OSDM#531]
An exchangeOffer consists of **admissionOfferParts**, **reservationOfferParts** and **ancillaryOfferParts**.

The **admissionOfferParts** holds a single admissionOfferPart opposed to a list like the other offerParts, the non-exchange Offer and BookedOffers.

```
"admissionOfferParts": {admissionOfferPart}
```

to
```
"admissionOfferParts": [{admissionOfferPart}]
```

This is considered as a bug and blocks implementing the exchange flow where an offer can consist of different admissionOfferParts.

This bug occurs in v3.0.x and above. v3.0.3 is used on multiple (production) implemented where exchange support is needed, therefor we need it to be back ported.

**Comment by jspetrak** [comment]
Agreed. This needs a fix. But we have to do it in non-breaking manner even though that the original one will not be used any more.

**Comment by CGantert345** [comment]
Bug fixing in:

3.0.4, 3.1, 3.2,   --> new releases
3.3  


TODO: Clemens, Josef

**Comment by rolandkla** [comment]
Thanks @CGantert345 @jspetrak
