### ISSUE TITLE
RefundOfferBreakdown should contain an array of items

### ISSUE THREAD

**Issue by schlpbch** [UnionInternationalCheminsdeFer/OSDM#544]
Similar to the `ExhcangeOfferBreakdown` the `RefundOfferBreakdown` should contain an array of items:

![image](https://github.com/UnionInternationalCheminsdeFer/OSDM/assets/18540761/5c25f86c-bb04-40dc-a8cf-11ab0aabea16)

**Comment by jspetrak** [comment]
TODO change to array - Andreas

**Comment by schlpbch** [comment]
Needed to be clarified further:

- inconsistent spelling of breakdown
- unclear what the different is between `exchangeBreakdown` and `exchangeOfferBreakdown`

**Comment by schlpbch** [comment]
fixes are merged

**Comment by schlpbch** [comment]
fixes are merged
