### ISSUE TITLE
Clarify/remove status on level compartement/vehicle in /availabilities/place-map

### ISSUE THREAD

**Issue by schlpbch** [UnionInternationalCheminsdeFer/OSDM#546]

**Comment by KlausKovar** [comment]
At the moment the attribute "status" is mandatory at level coach, compartment and places.

**Comment by jspetrak** [comment]
I think we discussed that before the Samtrafiken NDS launch and the resolution was that it is precomputed shorthand indicating summary availabiliry for coach, compartment, ... for place it is always needed.

**Comment by schlpbch** [comment]
Reached out to PKP.

**Comment by CGantert345** [comment]
the isSelectable flag should stay. It is exactly what you need for the "private" compartments.

**Comment by jspetrak** [comment]
> the isSelectable flag should stay. It is exactly what you need for the "private" compartments.

Let's adjust the description to explain it for the further generations.

**Comment by schlpbch** [comment]
fixes are merged
