### ISSUE TITLE
Clarify layouts in /availabilities/place-map

### ISSUE THREAD

**Issue by schlpbch** [UnionInternationalCheminsdeFer/OSDM#547]
We have three layout ids

- `layoutId`
- `layoutLowerDeck` - should be  `layoutLowerDeckId`
- `layoutUpperDeck` - should be  `layoutUpperDeckId`

In case of two deck vehicles what is to be set on `layoutId`?

Proposal: `layoutId` denotes per definition the `layoutLowerDeck`.

**Comment by jspetrak** [comment]
ADD comment on layoutId that it links to layout combining both decks together if multiple decks are in the vehicle
