### ISSUE TITLE
POST Release references fulfillment, which causes issues with a through-fare

### ISSUE THREAD

**Issue by stinacarlstedt** [UnionInternationalCheminsdeFer/OSDM#560]
The POST Release endpoint takes a list of fulfillments as its input. This is not precise enough when a through-fare needs to be partially released (for instance during a traffic disturbance). Suggest adding an additional element to the body of the ReleaseOfferRequest including a list of reservationIDs (as found in the booking) to further quality the request.

![image](https://github.com/UnionInternationalCheminsdeFer/OSDM/assets/48951735/a1b09ef3-76eb-4edd-90e3-fd81ef2549e8)

**Comment by stinacarlstedt** [comment]
Candidate for 3.0.4

**Comment by CGantert345** [comment]
We need to define: 
  - are the fulfillments omitted in case reservationIds are used?
  - what if both is used? Need all referenced parts and the parts iof the fulfillments be released
  
We should then add admisiionIds and ancillaryIds as well to heve a release function based on offer parts instead of fulfillments.

**Comment by jspetrak** [comment]
> Candidate for 3.0.4

For tracking changes in different version we will create separate issues. Let's first agree on content of the change and we will make the tracking and changes of openapi files after that.

**Comment by stinacarlstedt** [comment]
To not make the change breaking, suggest keeping the option of using the fulfillments as well as the reservation.
Will add admission and ancillary (I suppose here the use case is releasing a bicycle space, as opposed to a meal?) and encase them in a oneOf structure for clarity. For version 4, maybe a more radical reworking can be made?
