### ISSUE TITLE
No "name" property in Place object? 

### ISSUE THREAD

**Issue by MaximeAnsquer** [UnionInternationalCheminsdeFer/OSDM#565]
Hello,

From the [ReDoc documentation for version 3.2.0](https://redocly.github.io/redoc/?url=https://raw.githubusercontent.com/UnionInternationalCheminsdeFer/OSDM/master/specification/v3.2/OSDM-online-api-v3.2.0.yml), I see that the Place object has an attribute `name`.   
However I cannot see this attribute in the file [OSDM-online-api-v3.2.0.yml](https://github.com/UnionInternationalCheminsdeFer/OSDM/blob/master/specification/v3.2/OSDM-online-api-v3.2.0.yml#L10261) present in this repository.
Could you help me clarify this point please?

**Comment by schlpbch** [comment]
I assume that is related to the fact that the current Swagger implementation does not support displaying inheritance correctly. `StopPlace`, `Address` and `POI` have the attribute `name` but not the super class `Place`.
