### ISSUE TITLE
Gender should be nullable?

### ISSUE THREAD

**Issue by benys** [UnionInternationalCheminsdeFer/OSDM#573]
Dear OSDM Team,

For most sale request gender is not required from "offer perspective".

In osdm specification gender doesn't have "nullable" enabled. 

Is it valid or not?

Kamil

**Comment by benys** [comment]
Hello,
Yes, I know, but we have a problem with C# language.

Swagger generator generate this "ENUM" as NOT NULLABLE, so if we create object by default constructor, always put "MALE" enum value as default.
I see that sometimes in swagger specification you decorate also by "nullable" attribute.

I changed generated code and set this property as nullable.

**Comment by jspetrak** [comment]
I can imagine the issue - I personally use Java (Spring) generator and there, the generator developers found out late that they interpret required and nullable incorrectly.

We will have to revise the whole spec if we use required and nullable property at each attribute in the next versions (we are now about to release 3.3.0 so this can be accommodated.)

I would use X as default if a gender is not known and must be filled in. That is value we introduced for Sweden for diverse sleeping compartments.

**Comment by schlpbch** [comment]
Do you have other attributes where this issue plagues you? 

It would be best, if you could join our weekly discussion on Friday 09:00 to 11:00 so that we can support you best,

**Comment by CGantert345** [comment]
TODO: define Gender nullable
