### ISSUE TITLE
Question on get /reduction-cards (materdata)

### ISSUE THREAD

**Issue by KlausKovar** [UnionInternationalCheminsdeFer/OSDM#583]
Regarding the get /reduction-cards endpoint: 

- I think this is now about reductioncardtypes
- we would like to add a travelClass attribute additionally to the serviceClassType
- is the mandatory id-attribute necessary in the name{} object? What would be the id of a "VorteilsCard" additionally to the text?
- do we need the translations[] here?

**Comment by CGantert345** [comment]
TODO: 
- split according to 4.0 and 3.4
   -  4.0 remove id from Text, rename end point to ReductionCardTypes
   - 3.4 deprecate id in Text , add optional travelClass 
   - 3.4 add comment on masterdata reduction cards to retuen all known cards (at least those where a reduction is granted)
-

**Comment by KlausKovar** [comment]
Created https://github.com/UnionInternationalCheminsdeFer/OSDM/issues/613 for the 4.0 changes.
