### ISSUE TITLE
Add graphical reservation indicator in bookedOffers.reservation

### ISSUE THREAD

**Issue by Linus-Turnit** [UnionInternationalCheminsdeFer/OSDM#592]
In reservationOfferParts we have a graphicalReservation indicator available. We miss that indicator in booking-context.

We would like to do a change in bookedOffers.reservations where it is possible to indicate in the a booked reservation that it is possible to call a graphical place-map to change places.

If it's possible we would like to have this in version 3.0.4 since place-map implementations will happen in Sweden this summer. 

![image](https://github.com/UnionInternationalCheminsdeFer/OSDM/assets/122451962/c2c09dee-afa9-4587-8d9f-4263b0787d74)

**Comment by Linus-Turnit** [comment]
We have a bank holiday this Friday so I can't participate in the meeting, but I hope this description is good enough.

**Comment by schlpbch** [comment]
Proposal

add `supportGraphicalREservation` as a Boolean to `ReservationBookingPart`. Defaults to `false`.

**Comment by schlpbch** [comment]
Needs to be added to 3.3.0 and lower version until 3.0.4.

**Comment by schlpbch** [comment]
Andreas provides a patch.

**Comment by CGantert345** [comment]
Added AvailablePlacePreferences, as the boolean on graphical reservation is not enough
