### ISSUE TITLE
Exposing refund value and refund fees in an AbstractOfferPart

### ISSUE THREAD

**Issue by rolandkla** [UnionInternationalCheminsdeFer/OSDM#593]
While introducing another operator in Sweden to the OSDM landscape we are analysing the refund values.

There are 2 options to expose the amount refunded during an after sales operation:
- in the confirmed `refundOffer` that refers to the refunded offerParts
- on the `offerPart` itself in the refundAmount property

The `refundAmount` property in the AbstractOfferPart can expose the refunded value. It is however not clear how the refund information can be exposed.

**The refundAmount value itself**
Is this the nett or gross value? And if it is nett, how should after sales booking fee's or ticket fee's be calculated? Example:
- fulfilment 1 value 100
- fulfilment 2 value 50
- fulfilment 3 value 100
- after sales booking fee of 10 (not per ticket but per single operation)

When these 3 fulfillments are cancelled in the same refundOffer operation, what value should be exposed in the `refundAmount` for each offerPart?
- fulfilment 1 refundAmount = 100 (gross)
- or refundAmount = 100 - 10/3 (guesstimated nett)
- or refundAmount = 100 - 10/pro rata (guesstimated nett)

Technically it is not correct to divide an overarching fee since there is no direct relation between a fee and the offerParts. Therefor our working assumption is that the refundAmount is gross

**Exposing applies after sales fees**
And how should the after sales fees be exposed? there is a feeRef but the fee's itself has no indication wether it was applied during booking creation or during after sales. Since we have a `bookedOffers[].offerPart.price` for the sales value, I expect the `bookedOffers[].offerPart.feeRefs[] +bookedOffers[].fees[]` to be sales fees. And the `bookedOffers[].offerPart.refundAmount` to be the refund value (gross) and have a `bookedOffers[].offerPart.refundFeeRefs + bookedOffers[].refundFees` for the refund financial data.

This way the client can determine:
- the gross amount = `AbstractOfferPart.refundAmount`
- the optionally deducted after sales fee = sum of `AbstractOfferPart.refundFeeRefs[] > `BookerOffers[].fees[]`
- nett refund = gross - after sales fee

Is it indeed intended to have different ways to expose refund values, both through refundOffers and offerParts? Is it recommended to favour the refundOffer since that is the actual refund operation?

**Comment by Linus-Turnit** [comment]
I would suggest that the operation fee is a new confirmed offer in the booking and refundAmount amount is omitted and replaced with offerPart.price since it always is 100% anyway and distributor must calculate the amount.

Eg. This use case gives 80% back of the price and have an refund operation fee of 50 SEK

```
{
	"bookedOffers": [
		{
			"offerId": "offer1",
			"summary": "2nd, class Stockholm C - Gothenburg C",
			"admissions": [
				{
					"objectType": "Admission",
					"id": "offerPart1",
					"price": "1000 SEK",
					"refundFee": "200 SEK",
					"status": "REFUNDED",
					"summary": "2nd, class Stockholm C - Gothenburg C",
					"reservationRefs": [
						{
							"id": "offerPart2"
						}
					]
				}
			],
			"reservations": [
				{
					"id": "offerPart2",
					"summary": "Seat reserved in carriage 5 seat 21",
					"refundFee": "0 SEK",
					"status": "REFUNDED"
				}
			]
		},
		{
			"offerId": "refundFeeOffer1",
			"summary": "Refund operation fee",
			"feeRef": "fee1",
			"fee": [
				{
					"objectType": "Fee",
					"id": "fee1",
					"price": "50 SEK",
					"status": "CONFIRMED"
				}
			]
		}
	]
}

```

**Comment by rolandkla** [comment]
Updated the PR with the changes discussed:
- transaction context: sales or after sales
- status on fee to indicate if the fee is provisional, confirmed or refunded
