### ISSUE TITLE
Need ownerRef in GET /layout/{layoutId}

### ISSUE THREAD

**Issue by Linus-Turnit** [UnionInternationalCheminsdeFer/OSDM#601]
In a distributed multi carrier landscape Meta data end points is missing an owner attribute and parameter to divide the data between different owner (carriers).

The most important resource to handle in Sweden is layouts. We suggest to make a new endpoint 

![image](https://github.com/UnionInternationalCheminsdeFer/OSDM/assets/122451962/6853b11e-951d-4d69-bde5-b11416c569db)

Also the response need the ownerRef to make it more transparent
![image](https://github.com/UnionInternationalCheminsdeFer/OSDM/assets/122451962/2bcb4f14-a27b-46bd-979d-13dab3a06a1b)

We currently do not use any other Metadata endpoints but probably the same problem are applicable for at least products resources.

**This is quite urgent in Sweden since the place-map is on top of our development this summer/autumn, so we want to have this in version 3.0.***

**Comment by schlpbch** [comment]
Proposal

Model layout-id as a pair consisting of (layout,provider)
