### ISSUE TITLE
discrepancy on the level where to retrieve/specify fulfillmentOptions

### ISSUE THREAD

**Issue by nixxus1030** [UnionInternationalCheminsdeFer/OSDM#603]
There is discrepancy between the level at which we provide the availablefulfillmentOptions on offerpart level, while we can define what we need on booking level

Benerail proposal: add an availablefulfillment option on offer & booking level

**Comment by CGantert345** [comment]
POST bookings:  missing: requestedFulfillmentType preferredFulfillmentMedia

--> add requestedFulfillmentType preferredFulfillmentMedia on offer level

**Comment by CGantert345** [comment]
Add in bookingPart: confirmedFulfillmentOption: the option that would be choosen if the booking is confirmed.

**Comment by nixxus1030** [comment]
OK => can be implemented
