### ISSUE TITLE
Request Body must be marked as required where applicable

### ISSUE THREAD

**Issue by jspetrak** [UnionInternationalCheminsdeFer/OSDM#616]
Bileto is currently upgrading openapi generator to the latest version 7.7.0 and its Java generator got fixed logic to handle json nullable/optional cases. Now the generator produces request body as optional where it doesn't make any sense, e.g.

- POST /offers - you have to have some request parameters to provide
- POST /bookings/{bookingId}/fulfillments
- POST /bookings/{bookingId}/refund-offers
- PATCH /bookings/{bookingId}/purchaser - not sure if providing null requests means to delete the purchaser alltogether
- PATCH /bookings/{bookingId}/passengers/{passengerId} - does providing null passenger data means to delete all passenger details? or the once not needed for pricing?
- POST /bookings-search
- POST /places

The patch is to add `required: true` for any body object that must be provided.

Formally this is breaking change, but we consider it to be a bug since empty requests are not valid use case.

**Comment by CGantert345** [comment]
TODO josef branch for 4.0 and 3.4
