### ISSUE TITLE
Clarification: TransferLeg vs ContinuousLeg

### ISSUE THREAD

**Issue by jspetrak** [UnionInternationalCheminsdeFer/OSDM#617]
What is the difference?

- `TransferLeg` description: _A leg which links other legs of a trip where a transfer between different places is required. Provided by OJP._
- `ContinuousLeg` description: _A leg of a journey that is not bound to a timetable. Provided by OJP._

Our understanding: transfer leg is walk between stations/terminals in multi-modal journey or at major rail stations (platform groups at München Hbf for example), continuous leg is for any on-demand, new mobility, or very high-frequency timetables transport where timetable is not provided.

Possible bug:

`TransferLeg` object has both `TransferMode` and `ContinuousMode`, ContinuousLeg doesn't have any mode.

**Comment by CGantert345** [comment]
Continuous leg seems to be incomplete, there is no provider of the continuous service included

**Comment by jspetrak** [comment]
The leg structures will be reworked as part of OJP 2.0 #621
