### ISSUE TITLE
dwelltime format in POST tripCollection is unclear

### ISSUE THREAD

**Issue by nixxus1030** [UnionInternationalCheminsdeFer/OSDM#626]

**Comment by nixxus1030** [comment]
the element referes to the $duration standard openAPI type (follows RFC3339) so no need to further describe the format further. However the example is wrong cf the RFC to make a correct one

**Comment by CGantert345** [comment]
TODO update the example in the spec

**Comment by nixxus1030** [comment]
Double-checking the RFC (appendix A) https://www.rfc-editor.org/rfc/rfc3339, it does seem the example is correct
