### ISSUE TITLE
what if our timetable differs from the requested section timetable (while part of a larger trip)

### ISSUE THREAD

**Issue by nixxus1030** [UnionInternationalCheminsdeFer/OSDM#629]
When requesting an offer using tripspecification, it can happen that the provider timetable have a slightly different solution than the one in the specification. What should we do in this case ? what is the expected behavior

**Comment by nixxus1030** [comment]
For DB, a slight different delay should be accepted. Rationale is avoid failed booking for divergences that actually have not impact. Responsibility of validating the final combination of offers is to the consumer
For benerail, exact match is needed to avoid proposing impossible trips. Seen as a consequence of choosing the tripspecification approach. To get variations, the tripsearch should be used instead
Trenitalia considers they could end up with completely different proposal, but this is exactly why tripspecification exists: to get a specific trip

**Comment by nixxus1030** [comment]
questions:
 * what are the acceptable deviation for still considering the tripspecification to be equivalent ? different train number,different traintype ? 1, 2 minutes more ? both deviations at the same time ? => is IR 554 departing at 10:14 and arriving at 11:04 the same as BUS R554 departing at 10:06 and arriving at 11:08 (which is a plausible swap in case of works on the rails)
 * since tripspecification then also requires reconciliation, what is the added value.difference with tripsearch ?
 * * not receiving alternative routes
 * * still allows requesting routes that would not be part of the standard response set of the provider => requestor has control on proposed routes
 * *

**Comment by Azurab** [comment]
Our (PKP) first impression was that tripSpecification is for "manual mode": a short path skipping trip planning step (like form A-to-B points trip with obvious or on-boarded train regional validity) for employee-operated distribution channels (like handhelds for onboard staff) and does no need for any validation with timetable.

**Comment by CGantert345** [comment]
tripSpecification is used in case the consumer runs its own search engine for journeys. This is the main use case between railways and also in many cases with ticket vendors. It is essential to allow this use case to enable a neutral search for journeys not biased by carriers.

**Comment by jspetrak** [comment]
@Azurab It is also used for manual entry when the purchaser needs exact train numbers, e.g. when requesting standalone reservations.
