### ISSUE TITLE
Wiki minute dates wrong for the last few

### ISSUE THREAD

**Issue by VelvetteRld** [UnionInternationalCheminsdeFer/OSDM#631]
Hello,

While browsing the [meeting notes](https://github.com/UnionInternationalCheminsdeFer/OSDM/wiki/meeting-minutes) I realized that the last 3 meeting minutes are marked as having happened in 2025 and not 2024. Since I do not have edit rights I am opening this issue.

What is expected: dates located in the past or present
What is seen: dates in the future such as

- 2025-07-26
- 2025-07-19
- 2025-07-12

Velvette

**Comment by jspetrak** [comment]
Fixed. Thanks!
