### ISSUE TITLE
Make requestor field optional

### ISSUE THREAD

**Issue by nixxus1030** [UnionInternationalCheminsdeFer/OSDM#632]
the requestor header description now states

> <span><span>
Requestor *string(header) | The  requestor header contains detailed information about who is calling the  API. It can include information such as channel, organization, sales  unit or workstation id and be used to configure e.g. the fare range  provided to the caller. The content of the string is part of a bilateral  contract by the two parties and not standardized by OSDM. It is  recommend to encrypt the information transferred.
-- | --

</span></span>
This proves to be a bit vague to know what kind of information it can be and to what end. This is especially annoying as it is a mandatory field

**Comment by CGantert345** [comment]
TODO:

define a structure that can be used instead of a bilateral structure?

can include an id of a requestor in the provider system. The requestor is defined bilaterally between consumer and provider.


make it optional in 3.4 and 4.0

**Comment by Azurab** [comment]
Hi, 
It is a good idea to achieve alignment among carriers in this field, at least those who are members of the UIC. Proposal for Requestor serialization:
org: - id of a requestor company (in case of UIC retailer or TCO, a RICS code),
ou: - id of a requestor (retailer) organizational unit (can be relevant for bilateral contracts business constraints),
distributor: - id (RICS code in case of UIC members) of a distributor company that is called (in case when more than one distributor are available through one OSDM gateway),
pointOfSaleId: - UIC POS location code (station code in many cases),
terminalId: - id of retailers device.

**Comment by jspetrak** [comment]
Requestor optionality will be handled in #696
