### ISSUE TITLE
BookedOfferResponse capacity

### ISSUE THREAD

**Issue by Azurab** [UnionInternationalCheminsdeFer/OSDM#643]
Hello.
Why BookedOfferResponse is restricted to only one BookedOffer (with many bookedOffer ids reference) if an array of many offers selection is available in the request?

**Comment by jspetrak** [comment]
@Azurab Which API endpoint?

**Comment by Azurab** [comment]
Post: /bookings/{bookingId}/booked-offers (a question referring to #/components/schemas/BookedOfferRequest' and '#/components/schemas/BookedOfferResponse').

**Comment by jspetrak** [comment]
In 3.0.0, there was only BookedOfferResponse.bookedOffer in the response, in 3.0.3, BookedOfferResponse.bookedOfferIds was added to support response for adding more than one additional offers to booking. `bookedOfferIds` must be always provided. `bookedOffer` may be null and booking should always be re-fetched after the operation using GET /bookings/ID

TODO - Discuss if BookedOfferResponse.bookedOffer should be deprecated in 3.4.0 and removed in 4.0.0 completely.

**Comment by CGantert345** [comment]
Decision: remobe bookedOffer in version 4.0 and deprecate it in 3.4

**Comment by jspetrak** [comment]
@CGantert345 It was already deprecated in 3.4.0. I created PR to remove the property in 4.0.0.
