### ISSUE TITLE
Calendar dates are date-time but should be date

### ISSUE THREAD

**Issue by elNonok** [UnionInternationalCheminsdeFer/OSDM#644]
Hello,

If I understand its description correctly, the Calendar dates field is an array that allow us to optionally restrict the calendar (used in POST /offers resource response : offers.fares.travelValidityConstraint) to certain dates within the global range defined by "from" and "until" fields which are date-time (and I understand why). 

But what is the meaning of the time part of these dates ? 

For exemple :
```
{
    "validTravelDates": 
    {
        "dates": ["2024-08-04T00:00:00.000+02:00","2024-08-11T00:00:00.000+02:00","2024-08-18T00:00:00.000+02:00","2024-08-25T00:00:00.000+02:00"],
        "from": "2024-08-01T00:00:00.000+02:00",
        "until": "2024-08-31T23:59:59.999+02:00"
    }
}
```
In this exemple, what is the meaning of the time part of the dates ? Is the travel possible only at midnigth ?

I suggest changing the dates type to date without any time like this :
```
{
    "validTravelDates": 
    {
        "dates": ["2024-08-04","2024-08-11","2024-08-18","2024-08-25"],
        "from": "2024-08-01T00:00:00.000+02:00",
        "until": "2024-08-31T23:59:59.999+02:00"
    }
}
```
Which means that the travel can be done between the first and last days of august and more precisely the 4, 11, 18 or 25.

Thanks in advance for your time.

**Comment by CGantert345** [comment]
TODO: add documentation on using the offset as time zone indication for the date.

**Comment by elNonok** [comment]
Oh yes : I don't use the utcOffset field because I include it directly in each date-time like it's defined by ISO 8601. 
I think it's simpler to do it this way because the frameworks know how to handle it correctly.

For the offset format it can be +XX:XX or Z but I personaly use the first format in my test environment, just because it directly display me the time in my locale it's simplier to understand for an human but for a machine the Z format is more generic. In any case, the frameworks should know how to deal with the 2 formalisms.

**Comment by elNonok** [comment]
Hey! I saw your PR and I don't meet your explanation. 
It actually explain me why the utcOffset field should be use with dates, but including it on every date with an arbitrary and useless time for each date seems a bad like a bad design to me.

**Comment by CGantert345** [comment]
TODO: change it to date in version 4.0.
