### ISSUE TITLE
City passes in OSDM

### ISSUE THREAD

**Issue by JorienDT** [UnionInternationalCheminsdeFer/OSDM#650]
Are additional city passes for cities like Zurich and Geneva (SBB) an ancillary or an admission pass?

**Comment by CGantert345** [comment]
They are admissions. According to the definition (https://osdm.io/spec/models/) admissions represent a travel right whereas ancillaries don't.

**Comment by jspetrak** [comment]
@CGantert345 @schlpbch I am looking into swagger, and we can express desired regional validity in request OfferSeachCriteria, admissionOfferPart contains textual summary but no structured regional validity data, and admission in bookerOffer doesn't contain anything to recognize the regional validity expect maybe textual label in summary or from the product. Is that correct?
