### ISSUE TITLE
Passenger variants like female, military or students

### ISSUE THREAD

**Issue by JorienDT** [UnionInternationalCheminsdeFer/OSDM#651]
How are female seats handled? E.g. when it is requested to only have 2 females next to each other.
How are military and students handled? Discounts or passenger types?

**Comment by CGantert345** [comment]
Military and student are handled via reduction cards. Seats for female travelers can be offered by providing the possible seat types (similar to seats in silence or family areas) in the reservation offer.

**Comment by JorienDT** [comment]
Thanks for clarification!
