### ISSUE TITLE
Passengers in booking flow

### ISSUE THREAD

**Issue by JorienDT** [UnionInternationalCheminsdeFer/OSDM#652]
While checking OSDM booking flow, we stumbled upon a few use cases that we would like to have your support clarifying: 
1. Price changes after price locking: If a retailer requests Patch /bookings/{bookingId}/passenger to update one of the passenger details (age, reduction card...), and the update results in a price change, how will the retailer be informed of the price change before confirming the booking through /bookings/{bookingId}/fulfillments 
2. Carriers support setting pax data on different steps (outlined under Requested Information per Process Step in https://osdm.io/spec/processes/ ). We have carriers (such as SBB) that require sending pax data to lock the price and do not allow any pax data updates afterward. How are distributors expected to map Patch /bookings/{bookingId}/passenger in those cases? Should the distributor throw a warning that the operation is not supported by the carrier?

**Comment by CGantert345** [comment]
TODO documentation: seguence diagramm on patch passenger and get booking to see price changes

TODO make the documentation on required data more visible

**Comment by CGantert345** [comment]
additionally add grammer page to documentation

**Comment by jspetrak** [comment]
The grammar is linked here https://osdm.io/spec/processes/#AddingInformation
