### ISSUE TITLE
The description of the departureTime and arrivalTime in tripSearchCriteria should indicate one is mandatory

### ISSUE THREAD

**Issue by nixxus1030** [UnionInternationalCheminsdeFer/OSDM#664]
At the moment there is no explicit indication that when using tripSearchCriteria, at least one of departureTime and arrivalTime have to be filled in.

Proposal is to adapt the description of the attribute to specify this

**Comment by jspetrak** [comment]
@nixxus1030 It was partially described in the openapi spec., but I pulled a change to have a clearer definition. Please review.
