### ISSUE TITLE
ExchangeOfferBreakDown and exchangeBreakdown in exchangeOffers

### ISSUE THREAD

**Issue by Azurab** [UnionInternationalCheminsdeFer/OSDM#665]
Hi.
Please make me sure that:
* exchangeOfferBreakDown is for offerParts that will exist in future ExchangeOperation:exchangeOffers,
* exchangeBreakdown is for BookedOfferParts will not exist in future ExchangeOperation:exchangeOffers (will remain in status EXCHANGED).

**Comment by jspetrak** [comment]
exchangeOfferBreakDown is used in ExchangeOffers that are only created for Fulfillments of Products that allows to be exchanged. Also, breakDown is optional to provide. Samtrafiken uses that feature for multi-leg multi-modal/multi-carrier admissions or reservations, or when multiple passenger categories are on the admission so they provide details on what is going to be exchanged.

**Comment by jspetrak** [comment]
@Azurab Where did you find `exchangeBreakdown`?

**Comment by Azurab** [comment]
Hint: 
#/components/schemas/ExchangeOfferCollectionResponse
#/components/schemas/ExchangeBreakDown
Frankly, I still do not understand the difference between exchangeOfferBreakDown and exchangeBreakdown.

**Comment by jspetrak** [comment]
`ExchangeOfferCollectionResponse` is response envelope that contains the actual `ExchangeOffer` resources and other contextual API resources like Trips and Passengers. `ExchangeBreakDown` is optional content of an `ExchangeOffer ` if you the provider wants, or API consumer needs to break down how is each booking part refunded (what is refunded amount, and fee).

Exact name `exchangeBreakdown` is not in the API. That's why I ask where do you see it.

**Comment by Azurab** [comment]
> API consumer needs to break down how is each booking part refunded (what is refunded amount, and fee).

So what is ExchangeOfferBreakDown (array of ExchangeOfferItems) for?

**Comment by jspetrak** [comment]
You have to have ExchangeOffer if you allow exchange of one Fulfillment for another. It contains only summary exchangeFee, exchangePrice.

ExchangeOfferBreakDown is optional breakdown if you have more than one booking parts in single Fulfillment, or exchange more Fulfillments in single Exchange Offer, you may or may not provide the breakdown, what is exchangeFee, exchangePrice and refundableAmount for one or more parts. It is not required to provided. But if distributor wants to always provide that or the retailer needs to know that, this is the structure how to provide the information.

**Comment by Azurab** [comment]
Thank you. We calculate fee, price and the balance for every elementy in exchange transactions in detail "by design".
