### ISSUE TITLE
Exchange flow : how to filled the exchangePrice section

### ISSUE THREAD

**Issue by NicolasAU35** [UnionInternationalCheminsdeFer/OSDM#670]
Hi,
We have a question about the exchange flow.
In the POST /bookings/exchange-operations, how should be filled the section exchangePrice ?
Should we displayed in this field the amount of new tickets or the amount the customer have to pay for exchange transaction (or be reimburse in case of negative balance) including fees.

Best regards,
Nicolas

**Comment by jspetrak** [comment]
We probably need to introduce a property similar to provisionalRefundAmount in Booking to handle negative balance of exchange (money returned to the purchaser).

**Comment by Azurab** [comment]
I thought negative balance was invaild in exchange-offers (Reimbursement methods are designed for such use case). Improvement of after-sales documentation is needed.

**Comment by CGantert345** [comment]
refundableAmount missing in exchange offer --> Josef
