### ISSUE TITLE
Addition of set value OPERATOR_APP for FulfillmentMediaType

### ISSUE THREAD

**Issue by stinacarlstedt** [UnionInternationalCheminsdeFer/OSDM#672]
Distinct from RETAILER_APP, since the seller needs to know not to display it in thier app. Largely for digital travel passes.

**Comment by jspetrak** [comment]
I belive that operators are technically distributors if the both provide their fares, and bundle offers from them.

**Comment by stinacarlstedt** [comment]
Non-breaking update: add a CompanyRef attribute within the FulfillmentDocuments structure:
![image](https://github.com/user-attachments/assets/f6f1e541-7990-4dbd-8b6e-9c00dd34928a)

and extend the enum:
![image](https://github.com/user-attachments/assets/c4e22231-3a71-4559-99bb-bcaaa3e23cc3)

**Comment by CGantert345** [comment]
TODO: Josef
