### ISSUE TITLE
Set template for issue documentation

### ISSUE THREAD

**Issue by stinacarlstedt** [UnionInternationalCheminsdeFer/OSDM#673]
The issue list doubles as release notes, and if we standardise the way we document decisions, this gives a lot of valueable information after the fact. Best in class issue: https://github.com/UnionInternationalCheminsdeFer/OSDM/issues/449

**Comment by stinacarlstedt** [comment]
_Suggested template_:

### Description of change:
_text explaining the nature of the change_

### Why do we want this change, what problem are we trying to solve?
_rationale for making the change, detailing either a new need or a flaw in the existing implementation_

### Details on what has changed:
* _element_ added in _class_
* _element_ made optional
* _element/class_ deprecated
* _code_ added in code list or enum
* documentation updated
* etc..

### Proposed solution
\<yaml update\> or PR


### Reviewed with participants:
* ...
* ...
* ...

**Comment by CGantert345** [comment]
Template was added to the wiki
