### ISSUE TITLE
Improve documentation on versioning - clients should avoid strict validation

### ISSUE THREAD

**Issue by nixxus1030** [UnionInternationalCheminsdeFer/OSDM#674]
OSDM providers/consumers should avoid strict validation to avoid messages being rejected based on differences between two minor versions within the same major version. This point should be added to the documentation as a nadditional design guideline

**Comment by CGantert345** [comment]
TODO (patch CG):
- move the versioning from wiki to technical principals
- add a description that the tolerant reader pattern must be implemented
