### ISSUE TITLE
Class not used?

### ISSUE THREAD

**Issue by stinacarlstedt** [UnionInternationalCheminsdeFer/OSDM#681]
ExchangeOfferItem not referred to by anything in 3.4 - can it be removed?

**Comment by stinacarlstedt** [comment]
Also PlaceAvailabilitiesResponse not used?

**Comment by jspetrak** [comment]
> PlaceAvailabilitiesResponse

Seems we have two similar objects - the used one is `PlaceAvailabilitiesResponse`.

**Comment by CGantert345** [comment]
TODO: Stina pull request

**Comment by CGantert345** [comment]
TODO: Josef

**Comment by jspetrak** [comment]
FYI PlaceAvailabilitiesResponse  is used in 4.0.0 I wonder how that got to 3.4.0 draft but we can safely remove.

**Comment by jspetrak** [comment]
ExchangeOfferItem was superseded by ExchangeBreakdownItem in ExchangeOffer.exchangeOfferBreakdown
