### ISSUE TITLE
Indicator for a fulfilment without a document and part

### ISSUE THREAD

**Issue by rolandkla** [UnionInternationalCheminsdeFer/OSDM#683]
**Context**

A fulfilment contains ticket information such as the control number, status and its related document(s). It is possible that an OSDM provider returns a fulfilment (because of the control number and status) but it does not return any documents or parts.
This is the case where a distributor generates the documents on behalf of the provider.

In this case, when an OSDM client fetches a booking it is not aware if the documents/parts are yet to be generated or if they will remain absent on purpose. This could lead to clients polling without result.

**Potential solution**
Extending the fulfilment object with an indicator to inform the client that documents/parts should be expected, then the client knows if it has to wait for documents or not.
This can be achieved by introducing a status or a property indicator.

**Comment by CGantert345** [comment]
Proposal:

add an indication "ContentComplete" in Fulfillment:
- false: content or additional content (documents or fulfillment parts) will be provided.
- true: content (documents or fulfillment parts) provided iscomplete. If no content is included this is intentional.

TODO: pull request Josef
