### ISSUE TITLE
trip_specification_booking_reservation_only

### ISSUE THREAD

**Issue by ralfbayer-db** [UnionInternationalCheminsdeFer/OSDM#686]
Book a standalone reservation based on a trip specification

**Comment by jspetrak** [comment]
@ralfbayer-db If that is a OTST scenario suggestion, we have separate github repo now: https://github.com/UnionInternationalCheminsdeFer/OSDM-testing/issues

**Comment by ralfbayer-db** [comment]
How do I move this issue to the Test Specification Project?

**Comment by jspetrak** [comment]
@ralfbayer-db I will copy it.
