### ISSUE TITLE
Special conditions for blind PRMs and PRMs in wheelchair

### ISSUE THREAD

**Issue by CGantert345** [UnionInternationalCheminsdeFer/OSDM#692]
NRT Tariff defines different rules for Blind Persons, Persons in a Wheechair and other PRMs.

To model that passenger "sub" types for "blind" and "in wheelchair" and a "neigther-blind-nor-wheelchair" PRMS and wheelchair-PRMs are needed. 

![Uploading image.png…]()

**Comment by CGantert345** [comment]
Proposal:  use reduction card to model this. 

- additional element in reduction card in case the number of codes is large
- additional reduction card codes in case of a low number of codes

**Comment by ralfbayer-db** [comment]
According to DB's PRM business department, the "subtypes" of the EU document are not yet 100% clear. In the German market, we currently use these values:

- B (Begleiter) - free accompanying person, another person travels for free with the PRM.
- G/aG (Gehbehindert / außergewöhnlich Gehbehindert) - the "actual" reduced mobility, i.e. crutches, wheelchair, other aids
- 1.Kl (1. Klasse) - 1st class. This is specifically for veterans who can travel 1st class with a 2nd class ticket

there are more possible values on the German document, most of which have no influence on the ticket sales process or the rights with public transport
- H (Hilflosigkeit) - helpless
- Bl (Blind) - blind
- Gl (Gehörlosigkeit) - deaf
- TBL (Taubblindheit) - blind & deaf
- RF (Rundfunk/Fernsehen) - does not have to pay for the radio/TV license

As you can guess, in Germany there are also local values only given out in some regions:
- HS (Hochgradig Sehbehindert) - extremely vision impaired
- T (Teilnahmeberechtigt am Sonderfahrdienst) - can use the special driving service

Also, PRMs in Germany can buy a "Wertmarke" (Stamp), which gives them free transport in the local public transport (regional trains, buses, trams etc.).

**Comment by CGantert345** [comment]
tariff conditions should be reconsidered.
