### ISSUE TITLE
Carrier for international Tickets

### ISSUE THREAD

**Issue by patrickludwig77** [UnionInternationalCheminsdeFer/OSDM#707]
For international crossboarder tickets, the carrier code (as example 1185) must be printed on the ticket.
The distributor should be able to print it, based on information he gather from the fare provider.

I have expected such a parameter at the endpoint of the offer in the fare part, but it is not available there.

I suggest adding this parameter as a mandatory parameter.

**Comment by CGantert345** [comment]
The carrier(s)  are part of the regional validity of the fares in the offer. The carriers can be related to the entire route of parts of it.

![image](https://github.com/user-attachments/assets/be7985a8-9c56-417b-8be5-b32daf160839)

**Comment by patrickludwig77** [comment]
Thanks @CGantert345 , I already saw that, but I had a different interpretation.

Still, I think it would make sense to define this value as mandatory as it is required for cross-border tickets and the aim of the fare is to use it in a cross-border context. 
I fear, when it is not defined as madatory, some will deliver it, some not and at the end we have a heterogenious situation

**Comment by jspetrak** [comment]
@patrickludwig77 Isn't such desired parameter the `Fulfillment.issuer`? Nevertheless, OSDM is multi-modal standard and I believe that such required property would not work outside the rail sector.

**Comment by patrickludwig77** [comment]
Hi @jspetrak 
No, issuer and carrier is not the same. 

- Issuer is the on generating (issuing) the ticket and the one who has to guarantee for the custommer rights and pay any compensations in case of delay and so on.
- The carrier is the one running the train.

This rules are based on UIC and especially for crossborder tickets both must be printed on the ticket. And therefore it must be available in the **fare**based approach. 
With all understanding for a multimodal model, from my point of view fields must be mandatory which are required by the regulator for certain usecases, especially when we like to define this model as standard for one (rail) sector.
I do not know the rules given by EU law for other international transport sectors, but I assume the are similar than the one for rail.

When we do not dfine it as mandatory we will definitvley end in a hetergonious situation what we should prevent.

**Comment by CGantert345** [comment]
TODO Clemens: add comment on fare for carriercConstraint to have an obligatory carrier constraint on fare level including all carriers in the includedCarrier list.
