### ISSUE TITLE
Add more graphical items and introduce walls for coach layouts

### ISSUE THREAD

**Issue by oriolclosa** [UnionInternationalCheminsdeFer/OSDM#710]
At VR Snabbtåg (Sweden) we need to be able to build seatmaps that contain elements not available today in the catalogue of graphical items. In order to overcome this, we propose a few new icons.

The reason to add more window sizes is to be able to accomplish something similar to this. In here, we use two medium windows which "overflow" in both sides allowing a narrower "wall" without window with the big window placed in the middle with the table.

<img src="https://github.com/user-attachments/assets/4be73248-f55d-437f-aaaa-a3e558779915" width="500" />

We also think that it would be beneficial to indicate where coach entrances are located with a new sign. This can be specific to the entrances or simply show an arrow. In order to accomplish that we would need `direction` to be added on `internals` as requested on #709.

### Graphical icons

| **Icon** | **Description** | **Icon code** | **Orientation used** | **Mounting used** |
|---|---|---|---|---|
| ![image](https://github.com/user-attachments/assets/7855b01d-83ca-4f03-a2cf-6e4d06654373) | Small window, width covers one space | 173 (135) | — | — |
| ![image](https://github.com/user-attachments/assets/0ad3ca3a-06be-4fad-a963-4365dd19a05d) | Medium window, width covers two spaces | 174 | — | — |
| ![image](https://github.com/user-attachments/assets/534a1ba9-8587-42d2-99d0-cb02c65a8900) | Big window, width covers three spaces | 175 | — | — |
| ![image](https://github.com/user-attachments/assets/c5799cee-c7d5-4cde-bd4b-7853b3c5a720) | Door with left opening (traditional) | 176 | Left | — |
| ![image](https://github.com/user-attachments/assets/37f69c78-5a5e-4249-bbca-c5b75d0c887e) | Door with left opening (traditional) | 176 | Top | — |
| ![image](https://github.com/user-attachments/assets/9559972f-e531-4d97-b7f9-3b80de41daed) | Door with left opening (traditional) | 176 | Right | — |
| ![image](https://github.com/user-attachments/assets/f8cb6aa0-c104-418d-adf5-4767fd22f47f) | Door with left opening (traditional) | 176 | Bottom | — |
| ![image](https://github.com/user-attachments/assets/08089b90-a7e9-4f00-babf-2942a01a2627) | Door with right opening (traditional) | 177 | Left | — |
| ![image](https://github.com/user-attachments/assets/534ea5d9-8886-491f-9248-b95d31e91068) | Door with right opening (traditional) | 177 | Top | — |
| ![image](https://github.com/user-attachments/assets/d8dda5de-1492-425b-a705-beba0b483bac) | Door with right opening (traditional) | 177 | Right | — |
| ![image](https://github.com/user-attachments/assets/adc4c7ff-1b94-4d5d-bcc0-fc5d1a76956a) | Door with right opening (traditional) | 177 | Bottom | — |
| ![image](https://github.com/user-attachments/assets/2ed40dc2-353f-44e4-b92f-9a1512b8f7dd) | Door (sliding) | 178 | Top, bottom | — |
| ![image](https://github.com/user-attachments/assets/ad4aea71-e0f8-49e5-a0e9-60b17e2ad7d6) | Door (sliding) | 178 | Left, right | — |
| ![image](https://github.com/user-attachments/assets/f78b837a-2df9-407f-802b-b5417b2d5b01) | Entrance | 179 | Left | — |
| ![image](https://github.com/user-attachments/assets/17ddaa23-64d9-4daf-9ed4-881b72849ff0) | Entrance | 179 | Top | — |
| ![image](https://github.com/user-attachments/assets/0dae4d1a-1bc2-43de-af68-54f462b5e3d0) | Entrance | 179 | Right | — |
| ![image](https://github.com/user-attachments/assets/3baa8755-6f77-4424-97de-a2f27ae1a3b1) | Entrance | 179 | Bottom | — |

### Resolution

The way the seatmap is being implemented for the Swedish market takes into consideration the possibility that an icon can occupy more than one cell. For example a seat can be 40 cells wide allowing better placement of the objects due to, for example, tables not having the same width as seats. Therefore, it might be needed to introduce the concept of `width` and `height` for every `place`, `sign` and `internal`.

### Walls

As an additional improvement I feel like walls could simply be a set of vectors. This would allow more complex wall structures within each coach. By having a list of pairs of coordinates one can accomplish diagonal walls and any desired structure without the addition of new icons.

**Comment by CGantert345** [comment]
Icons will be added to the code list.

**Comment by oriolclosa** [comment]
Hello @jspetrak, I didn't have time yet to fix the icon table after our meeting last Friday but it's alright for us if we include all of them. We would still be missing the "small stairs" or maybe we could call it "steps".
