### ISSUE TITLE
Add residency to AnonymousPassengerSpecification for Eurail / Interrail passes

### ISSUE THREAD

**Issue by mvdgraaff** [UnionInternationalCheminsdeFer/OSDM#730]
**Name:**  Anonymous PassengerSpecification, add country of residence.
**Owner:** Eurail
**Description:**
Eurail and Interrail passes require the residency of a traveler to determine if the carrier regulations should be applied. When an anonymous passenger is living in Europe an Interrail pass should be offered, When the passenger is not living in the EU then an Eurail pass should be offered.

The regulation from the carriers have described that a EU resident can only travel one time outbound and one time inbound to its resident country and therefore can only buy an Interrail pass.  

In the OSDM offer request the anonymous passenger detail does not contain a residency element that can be used to create an adequate offer.  In the offer request the anonymous passengers list can contain non-eu/eu residents. The current setup is that Interrail/Eurail passes cannot be sold in one offer which is a not wanted limitation.

**Business value:** HIGH (For Eurail and Pass retailers)
**Business outcome:** The possibility to offer a combined interrail / Eurail passes to a group of non-eu/eu travelers.

**Comment by schlpbch** [comment]
Double checking: Having the country optional would fulfill your requirements, correct?

**Comment by jspetrak** [comment]
@schlpbch I am trying to imagine how we would do it currently?

1. Provide price offers for all options and "somehow" tag nationality eligibility (country validity can be indicated in `nonTripSearchCriteria.nutsCodes` in the request). 
2. Offer is selected and put into booking
3. Booking indicates in requiredInformation that nationality is required for passenger
4. When passenger is patched with country, booking fails if country doesn't match the offered country pass.

Unfortunately, only Fares have definition of countrains but do not describe nationality contraint for passenger.

We also do not have any mean to describe requiredInformation before obtaining the offer request.

If we would introduce optionally-required property, there must be some fail-safe process, e.g.

1. Offer request without passenger nationality is sent
2. API responds 200 OK with warning problem that offers can be offered after nationality is specified, problem pointer points to `#/anonymousPassengerSpecifications/[*]nationality`.
3. Refined offer request is sent
4. API responds 200 OK with pass offers.

**Comment by CGantert345** [comment]
The countryOfResidence is part of the passenger data: 
![image](https://github.com/user-attachments/assets/8ee2f220-fac9-451d-8e1b-b74c9ca51a90)

Having the countryOfResidence in the anonymousPasssenger Spec would be a special implementation for Eurail, which would probably be supported only by special eurail clients. Clients selling all kinds of products would not ask the passenger for thecountry of residence before requesting offers.
