### ISSUE TITLE
Add possibility to see validities for non-trip offers

### ISSUE THREAD

**Issue by Linus-Turnit** [UnionInternationalCheminsdeFer/OSDM#742]
For non-trip offers there is no possibility to see the the validity before the travelAccount is created for the pass. Reference id to the travelAccount is controlNumber, first available after fulfillment.

Suggested improvement is to add a new object, nonTripValidity, to the admissionOfferPart and the booked admission. I am open for other solutions but there is a need to have validity period and the regional constraints from the beginning somehow.

![image](https://github.com/user-attachments/assets/d9553d4b-8cb7-440c-813e-383218340117)

**The improvement is needed in 3.4 as well.**

**Comment by jspetrak** [comment]
The ideal place is under `regionalValiditySummary` of `AdmissionOfferPart`.

ValidFrom/ValidUntil are already parts of that object.

**Comment by jspetrak** [comment]
`regionalValiditySummary` should be in admission and ancillary only. reservation is always bound to vehicle number (trip).
