### ISSUE TITLE
Add more information to the asynchronous Post fulfillment response

### ISSUE THREAD

**Issue by nixxus1030** [UnionInternationalCheminsdeFer/OSDM#747]
Right now the asynchronous response has no body, while in many cases, while the complete specs of the fulfillment (typically the document link) is not needed yet, the id of the fulfillment is needed earlier.
It is possible to do via the syncrhonous response, but then to be really synchronous it would require generating the complete fulfillment. 
The proposal is to extend the body returned for the asynchronous call so that the id of the fulfillment can be returned in the asynchronous.

**Comment by jspetrak** [comment]
Make `Fulfillment.contentComplete` mandatory

202 to have same body as 200 in POST Fulfillment
