### ISSUE TITLE
Question : Why 2 differents date format in a same OSDM service

### ISSUE THREAD

**Issue by tgantz-connect** [UnionInternationalCheminsdeFer/OSDM#785]
Hello,

Is there any reason to have 2 different date format in a same OSDM service ?
For example, on POST /offers, there is 2 differents date format => "offset date time" format & "local date" format  
/offers/tripSpecifications/legs/timedLeg/start/serviceDeparture/timetabledTime => string <date-time> The time needs to be in Offset Time Format
/offers/tripSpecifications/returnSearchParameters/ => string or null(\d{4}-[01]\d-[0-3]\dT[0-2]\d:[0-5]\d:[0-5]\d) Needs to in local date time format.

**Comment by CGantert345** [comment]
In the request the local time is needed as the cliet does not know the time zone of the stations. The reply provides the local time and the offset, as the local  time is used for all information displayedto the passenger. The offset might be used to send notifications to the passenger.
