### ISSUE TITLE
website source

### ISSUE THREAD

**Issue by xthiba** [UnionInternationalCheminsdeFer/OSDM#810]
Hi,

i am reading through the specification section on osdm.io and notice spelling and other minor mistakes. Is the website source availble somewhere, so i can open PRs that fix these minor issues?

Thanks
Thilo

**Comment by jspetrak** [comment]
Hello, it is directly in this repo. Look for the markdown files. Feel free to contribute.

**Comment by xthiba** [comment]
i apologize - i couldnt find it in the master branch. sorry for that and thanks!
